#Project generated by Animated Java (https://animated-java.dev/)

schedule function gfreddy:animation_loop 1t
scoreboard players set .aj.anim_loop aj.gfreddy.animating 1
scoreboard players set .aj.animation aj.gfreddy.animating 0
execute as @e[type=minecraft:marker,tag=aj.gfreddy.root] run function gfreddy:zzz/execute/16
execute if score .aj.animation aj.gfreddy.animating matches 0 run function gfreddy:zzz/execute/17