#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation .this aj.id = @s aj.id
execute as @e[type=minecraft:armor_stand,tag=aj.backstage.bone,distance=..7.287] if score @s aj.id = .this aj.id run function backstage:set_variant/zzz/execute/13
scoreboard players set #execute aj.i 1