#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.gfreddy.root] run function gfreddy:animations/idle/zzz/conditional/16
execute if score #execute aj.i matches 0 run function gfreddy:animations/idle/zzz/conditional/17