#Project generated by Animated Java (https://animated-java.dev/)

tp @s ~ ~ ~ ~ ~
execute store result score @s aj.id run scoreboard players add .aj.last_id aj.i 1
execute at @s run function backstage:summon/zzz/execute/9
tag @s remove new
scoreboard players set @s aj.backstage.normal.loopMode 1
scoreboard players set @s aj.backstage.easter_egg.loopMode 1
scoreboard players set @s aj.backstage.game_over.loopMode 1
scoreboard players set @s aj.frame 0
scoreboard players set @s aj.backstage.animating 0