#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.foxy.bone.left_leg] ArmorItems[-1].tag.CustomModelData set value 1117
data modify entity @s[tag=aj.foxy.bone.left_lower_leg] ArmorItems[-1].tag.CustomModelData set value 1118
data modify entity @s[tag=aj.foxy.bone.right_leg] ArmorItems[-1].tag.CustomModelData set value 1119
data modify entity @s[tag=aj.foxy.bone.right_lower_leg] ArmorItems[-1].tag.CustomModelData set value 1120
data modify entity @s[tag=aj.foxy.bone.body] ArmorItems[-1].tag.CustomModelData set value 1121
data modify entity @s[tag=aj.foxy.bone.head] ArmorItems[-1].tag.CustomModelData set value 1122
data modify entity @s[tag=aj.foxy.bone.jaw] ArmorItems[-1].tag.CustomModelData set value 1123
data modify entity @s[tag=aj.foxy.bone.eyepatch] ArmorItems[-1].tag.CustomModelData set value 1124
data modify entity @s[tag=aj.foxy.bone.left_arm] ArmorItems[-1].tag.CustomModelData set value 1125
data modify entity @s[tag=aj.foxy.bone.left_hand] ArmorItems[-1].tag.CustomModelData set value 1126
data modify entity @s[tag=aj.foxy.bone.right_arm] ArmorItems[-1].tag.CustomModelData set value 1127
data modify entity @s[tag=aj.foxy.bone.right_hand] ArmorItems[-1].tag.CustomModelData set value 1128