#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.gfreddy.anim.idle
execute if score .aj.anim_loop aj.gfreddy.animating matches 0 run function gfreddy:animation_loop
scoreboard players set #execute aj.i 1