#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.left_door.bone.wall] run function left_door:animations/close/tree/wall_root_top
execute if entity @s[tag=aj.left_door.bone.door] run function left_door:animations/close/tree/door_root_top
execute store result entity @s Air short 1 run scoreboard players get .this aj.frame