#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/door/tree/jaw_display_0-7
execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [49.5832f,-34.9121f,-5.8925f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [49.5832f,-34.9121f,-5.8925f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [49.5832f,-34.9121f,-5.8925f]