#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/door/tree/left_hand_display_0-7
execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [52.5263f,1.5216f,89.4838f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [52.5263f,1.5216f,89.4838f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [52.5263f,1.5216f,89.4838f]