#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/door/tree/right_hand_display_0-7
execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [57.5247f,-1.3429f,-89.6089f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [57.5247f,-1.3429f,-89.6089f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [57.5247f,-1.3429f,-89.6089f]