#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.chica.bone.body] run function chica:animations/door/tree/body_root_top
execute if entity @s[tag=aj.chica.bone.left_arm] run function chica:animations/door/tree/left_arm_root_top
execute if entity @s[tag=aj.chica.bone.left_hand] run function chica:animations/door/tree/left_hand_root_top
execute if entity @s[tag=aj.chica.bone.right_hand] run function chica:animations/door/tree/right_hand_root_top
execute if entity @s[tag=aj.chica.bone.right_arm] run function chica:animations/door/tree/right_arm_root_top
execute if entity @s[tag=aj.chica.bone.left_leg] run function chica:animations/door/tree/left_leg_root_top
execute if entity @s[tag=aj.chica.bone.left_lower_leg] run function chica:animations/door/tree/left_lower_leg_root_top
execute if entity @s[tag=aj.chica.bone.right_leg] run function chica:animations/door/tree/right_leg_root_top
execute if entity @s[tag=aj.chica.bone.right_lower_leg] run function chica:animations/door/tree/right_lower_leg_root_top
execute if entity @s[tag=aj.chica.bone.head] run function chica:animations/door/tree/head_root_top
execute if entity @s[tag=aj.chica.bone.jaw] run function chica:animations/door/tree/jaw_root_top
execute if entity @s[tag=aj.chica.bone.eyes] run function chica:animations/door/tree/eyes_root_top
execute if entity @s[tag=aj.chica.bone.pupils] run function chica:animations/door/tree/pupils_root_top
execute if entity @s[tag=aj.chica.bone.eyelids] run function chica:animations/door/tree/eyelids_root_top
execute store result entity @s Air short 1 run scoreboard players get .this aj.frame