#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.freddy.root] run function freddy:animations/e_hall_corner/zzz/conditional/104
execute if score #execute aj.i matches 0 run function freddy:animations/e_hall_corner/zzz/conditional/105