#Project generated by Animated Java (https://animated-java.dev/)

summon minecraft:marker ~ ~ ~ {Tags:['foxy','new','aj.foxy','aj.foxy.root']}
execute as @e[type=minecraft:marker,tag=aj.foxy.root,tag=new,distance=..1,limit=1] rotated ~ 0 run function foxy:summon/zzz/execute/5
function foxy:assert_animation_flags