#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.backstage.game_over.loopMode matches 0 run function backstage:animations/game_over/stop
execute if score @s aj.backstage.game_over.loopMode matches 1 run function backstage:animations/game_over/pause
execute if score @s aj.backstage.game_over.loopMode matches 2 run function backstage:animations/game_over/zzz/execute/30