#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.backstage.root] run function backstage:animations/game_over/zzz/conditional/38
execute if score #execute aj.i matches 0 run function backstage:animations/game_over/zzz/conditional/39