#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.freddy.root] at @s run function freddy:animations/east_hall/zzz/conditional/90
execute if score #execute aj.i matches 0 run function freddy:animations/east_hall/zzz/conditional/91