#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if score @s aj.frame matches ..1 run function chica:animations/jumpscare/zzz/conditional/142
execute if score #execute aj.i matches 0 run function chica:animations/jumpscare/zzz/conditional/143