#Project generated by Animated Java (https://animated-java.dev/)

tag @s remove aj.bonnie.anim.show_stage
tag @s remove aj.bonnie.anim.dining_area
tag @s remove aj.bonnie.anim.w_hall_corner
tag @s remove aj.bonnie.anim.w_hall_corner_twitching
tag @s remove aj.bonnie.anim.supply_closet
tag @s remove aj.bonnie.anim.backstage
tag @s remove aj.bonnie.anim.backstage_creepy
tag @s remove aj.bonnie.anim.door
tag @s remove aj.bonnie.anim.jumpscare
tag @s remove aj.bonnie.anim.guitar
scoreboard players set @s aj.frame 0
scoreboard players operation .this aj.id = @s aj.id
execute as @e[type=minecraft:area_effect_cloud,tag=aj.bonnie.bone,distance=..6.294] if score @s aj.id = .this aj.id run function bonnie:zzz/execute/98
execute as @e[type=minecraft:armor_stand,tag=aj.bonnie.bone,distance=..6.294] if score @s aj.id = .this aj.id run function bonnie:zzz/execute/99
scoreboard players set #execute aj.i 1