#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set # aj.i 1
execute at @s as @e[type=#bonnie:bone_entities,tag=aj.bonnie.bone] if score @s aj.id = .this aj.id run function bonnie:zzz/execute/113