#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.bonnie.anim.show_stage] at @s run function bonnie:animations/show_stage/next_frame
execute if entity @s[tag=aj.bonnie.anim.dining_area] at @s run function bonnie:animations/dining_area/next_frame
execute if entity @s[tag=aj.bonnie.anim.w_hall_corner] at @s run function bonnie:animations/w_hall_corner/next_frame
execute if entity @s[tag=aj.bonnie.anim.w_hall_corner_twitching] at @s run function bonnie:animations/w_hall_corner_twitching/next_frame
execute if entity @s[tag=aj.bonnie.anim.supply_closet] at @s run function bonnie:animations/supply_closet/next_frame
execute if entity @s[tag=aj.bonnie.anim.backstage] at @s run function bonnie:animations/backstage/next_frame
execute if entity @s[tag=aj.bonnie.anim.backstage_creepy] at @s run function bonnie:animations/backstage_creepy/next_frame
execute if entity @s[tag=aj.bonnie.anim.door] at @s run function bonnie:animations/door/next_frame
execute if entity @s[tag=aj.bonnie.anim.jumpscare] at @s run function bonnie:animations/jumpscare/next_frame
execute if entity @s[tag=aj.bonnie.anim.guitar] at @s run function bonnie:animations/guitar/next_frame
scoreboard players operation @s aj.bonnie.animating = .aj.animation aj.bonnie.animating