#Project generated by Animated Java (https://animated-java.dev/)

tp @s[tag=aj.bonnie.bone.left_leg] ^0.2 ^-0.694 ^-0.062
tp @s[tag=aj.bonnie.bone.left_lower_leg] ^0.194 ^-1.171 ^-0.062
tp @s[tag=aj.bonnie.bone.right_leg] ^-0.2 ^-0.694 ^-0.062
tp @s[tag=aj.bonnie.bone.right_lower_leg] ^-0.2 ^-1.175 ^-0.062
tp @s[tag=aj.bonnie.bone.body] ^0 ^-0.694 ^-0.062
tp @s[tag=aj.bonnie.bone.head] ^0 ^0.506 ^-0.144
tp @s[tag=aj.bonnie.bone.eyes] ^0 ^0.906 ^0
tp @s[tag=aj.bonnie.bone.pupils] ^-0.005 ^0.906 ^0.03
tp @s[tag=aj.bonnie.bone.eyelids] ^0.001 ^0.943 ^-0.075
tp @s[tag=aj.bonnie.bone.left_ear] ^0.156 ^1.187 ^-0.112
tp @s[tag=aj.bonnie.bone.left_upper_ear] ^0.156 ^1.625 ^-0.112
tp @s[tag=aj.bonnie.bone.right_ear] ^-0.162 ^1.181 ^-0.112
tp @s[tag=aj.bonnie.bone.right_upper_ear] ^-0.162 ^1.625 ^-0.112
tp @s[tag=aj.bonnie.bone.jaw] ^0 ^0.587 ^-0.225
tp @s[tag=aj.bonnie.bone.right_arm] ^-0.362 ^0.268 ^-0.062
tp @s[tag=aj.bonnie.bone.right_hand] ^-0.925 ^0.268 ^-0.062
tp @s[tag=aj.bonnie.bone.left_arm] ^0.356 ^0.268 ^-0.062
tp @s[tag=aj.bonnie.bone.left_hand] ^0.919 ^0.268 ^-0.062
tp @s[tag=aj.bonnie.bone.guitar] ^-1.756 ^0.231 ^0.6
execute store result score .calc aj.i run data get entity @s Air
execute store result entity @s Air short 1 run scoreboard players add .calc aj.i 2