#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if score @s aj.frame matches ..1 run function bonnie:animations/guitar/zzz/conditional/152
execute if score #execute aj.i matches 0 run function bonnie:animations/guitar/zzz/conditional/153