#Project generated by Animated Java (https://animated-java.dev/)

tp @s ~ ~ ~ ~ ~
scoreboard players operation .this aj.id = @s aj.id
scoreboard players operation .this aj.frame = @s aj.frame
scoreboard players set # aj.i 0
execute if entity @s[tag=aj.chica.anim.show_stage] run function chica:zzz/execute/60
execute if entity @s[tag=aj.chica.anim.dining_area1] run function chica:zzz/execute/63
execute if entity @s[tag=aj.chica.anim.dining_area2] run function chica:zzz/execute/66
execute if entity @s[tag=aj.chica.anim.east_hall1] run function chica:zzz/execute/69
execute if entity @s[tag=aj.chica.anim.east_hall2] run function chica:zzz/execute/72
execute if entity @s[tag=aj.chica.anim.e_hall_corner] run function chica:zzz/execute/75
execute if entity @s[tag=aj.chica.anim.e_hall_corner_twitching] run function chica:zzz/execute/78
execute if entity @s[tag=aj.chica.anim.restrooms1] run function chica:zzz/execute/81
execute if entity @s[tag=aj.chica.anim.restrooms2] run function chica:zzz/execute/84
execute if entity @s[tag=aj.chica.anim.door] run function chica:zzz/execute/87
execute if entity @s[tag=aj.chica.anim.jumpscare] run function chica:zzz/execute/90
execute if score # aj.i matches 0 run function chica:zzz/execute/93
scoreboard players set #execute aj.i 1