#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.right_door.bone.wall] run function right_door:animations/open/tree/wall_root_top
execute if entity @s[tag=aj.right_door.bone.door] run function right_door:animations/open/tree/door_root_top
execute store result entity @s Air short 1 run scoreboard players get .this aj.frame