#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.024 ^0.437 ^-0.058 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.024 ^0.437 ^-0.058 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.024 ^0.437 ^-0.058 ~ ~