#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.05 ^0.549 ^-0.076 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.05 ^0.549 ^-0.076 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.05 ^0.549 ^-0.076 ~ ~