#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.854 ^0.057 ^0.119 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.854 ^0.057 ^0.119 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.854 ^0.057 ^0.119 ~ ~