#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.298 ^0.293 ^-0.211 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.298 ^0.293 ^-0.211 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.298 ^0.293 ^-0.211 ~ ~