#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [-26.1934f,32.4043f,-53.0114f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-26.1934f,32.4043f,-53.0114f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-26.1934f,32.4043f,-53.0114f]