#Project generated by Animated Java (https://animated-java.dev/)

summon minecraft:marker ~ ~ ~ {Tags:['gfreddy','new','aj.gfreddy','aj.gfreddy.root']}
execute as @e[type=minecraft:marker,tag=aj.gfreddy.root,tag=new,distance=..1,limit=1] rotated ~ 0 run function gfreddy:summon/zzz/execute/5
function gfreddy:assert_animation_flags