#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.5 ^0.594 ^2.179 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.5 ^0.594 ^2.179 ~ ~