#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.213 ^-0.558 ^-3.87 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.213 ^-0.558 ^-3.87 ~ ~