#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-2.282 ^-0.608 ^1.8 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-2.282 ^-0.608 ^1.8 ~ ~