#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-1.17 ^-0.337 ^1.869 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-1.17 ^-0.337 ^1.869 ~ ~