#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [9.2097f,-65.4679f,-76.1991f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [9.2097f,-65.4679f,-76.1991f]