#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [3.8603f,9.2319f,-67.1882f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [3.8603f,9.2319f,-67.1882f]