#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.gfreddy.bone.left_leg] ArmorItems[-1].tag.CustomModelData set value 460
data modify entity @s[tag=aj.gfreddy.bone.left_lower_leg] ArmorItems[-1].tag.CustomModelData set value 461
data modify entity @s[tag=aj.gfreddy.bone.left_foot] ArmorItems[-1].tag.CustomModelData set value 462
data modify entity @s[tag=aj.gfreddy.bone.right_leg] ArmorItems[-1].tag.CustomModelData set value 463
data modify entity @s[tag=aj.gfreddy.bone.right_lower_leg] ArmorItems[-1].tag.CustomModelData set value 464
data modify entity @s[tag=aj.gfreddy.bone.right_foot] ArmorItems[-1].tag.CustomModelData set value 465
data modify entity @s[tag=aj.gfreddy.bone.body] ArmorItems[-1].tag.CustomModelData set value 466
data modify entity @s[tag=aj.gfreddy.bone.left_arm] ArmorItems[-1].tag.CustomModelData set value 467
data modify entity @s[tag=aj.gfreddy.bone.left_lower_arm] ArmorItems[-1].tag.CustomModelData set value 468
data modify entity @s[tag=aj.gfreddy.bone.left_hand] ArmorItems[-1].tag.CustomModelData set value 469
data modify entity @s[tag=aj.gfreddy.bone.right_arm] ArmorItems[-1].tag.CustomModelData set value 470
data modify entity @s[tag=aj.gfreddy.bone.right_lower_arm] ArmorItems[-1].tag.CustomModelData set value 471
data modify entity @s[tag=aj.gfreddy.bone.right_hand] ArmorItems[-1].tag.CustomModelData set value 472
data modify entity @s[tag=aj.gfreddy.bone.head] ArmorItems[-1].tag.CustomModelData set value 473
data modify entity @s[tag=aj.gfreddy.bone.jaw] ArmorItems[-1].tag.CustomModelData set value 474