#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.backstage.anim.game_over
execute if score .aj.backstage.framerate aj.i matches ..-1 run scoreboard players set @s aj.frame 2
execute if score .aj.backstage.framerate aj.i matches 1.. run scoreboard players set @s aj.frame 0
scoreboard players add .noScripts aj.i 0
execute if score .aj.anim_loop aj.backstage.animating matches 0 run function backstage:animation_loop
scoreboard players set #execute aj.i 1