#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.foxy.bone.head] run function foxy:animations/stage_1/tree/head_display_top
execute if entity @s[tag=aj.foxy.bone.eyepatch] run function foxy:animations/stage_1/tree/eyepatch_display_top
execute if entity @s[tag=aj.foxy.bone.jaw] run function foxy:animations/stage_1/tree/jaw_display_top
execute if entity @s[tag=aj.foxy.bone.body] run function foxy:animations/stage_1/tree/body_display_top
execute if entity @s[tag=aj.foxy.bone.left_arm] run function foxy:animations/stage_1/tree/left_arm_display_top
execute if entity @s[tag=aj.foxy.bone.left_hand] run function foxy:animations/stage_1/tree/left_hand_display_top
execute if entity @s[tag=aj.foxy.bone.right_hand] run function foxy:animations/stage_1/tree/right_hand_display_top
execute if entity @s[tag=aj.foxy.bone.right_arm] run function foxy:animations/stage_1/tree/right_arm_display_top
execute if entity @s[tag=aj.foxy.bone.left_lower_leg] run function foxy:animations/stage_1/tree/left_lower_leg_display_top
execute if entity @s[tag=aj.foxy.bone.left_leg] run function foxy:animations/stage_1/tree/left_leg_display_top
execute if entity @s[tag=aj.foxy.bone.right_lower_leg] run function foxy:animations/stage_1/tree/right_lower_leg_display_top
execute if entity @s[tag=aj.foxy.bone.right_leg] run function foxy:animations/stage_1/tree/right_leg_display_top
execute positioned as @s run tp @s ~ ~ ~ ~ ~