#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function foxy:animations/stage_1/tree/left_arm_root_0-7
execute if score .this aj.frame matches 8..15 run function foxy:animations/stage_1/tree/left_arm_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0.464 ^0.134 ^0.344 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.464 ^0.134 ^0.344 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.464 ^0.134 ^0.344 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.464 ^0.134 ^0.344 ~ ~