#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function foxy:animations/stage_1/tree/left_arm_display_0-7
execute if score .this aj.frame matches 8..15 run function foxy:animations/stage_1/tree/left_arm_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [28.2347f,9.2754f,78.2079f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [28.2347f,9.2754f,78.2079f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [28.2347f,9.2754f,78.2079f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [28.2347f,9.2754f,78.2079f]