#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.foxy.root] at @s run function foxy:animations/stage_1/zzz/conditional/22
execute if score #execute aj.i matches 0 run function foxy:animations/stage_1/zzz/conditional/23