#Project generated by Animated Java (https://animated-java.dev/)

schedule function foxy:animation_loop 1t
scoreboard players set .aj.anim_loop aj.foxy.animating 1
scoreboard players set .aj.animation aj.foxy.animating 0
execute as @e[type=minecraft:marker,tag=aj.foxy.root] run function foxy:zzz/execute/28
execute if score .aj.animation aj.foxy.animating matches 0 run function foxy:zzz/execute/29