#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.chica.root] run function chica:animations/dining_area1/zzz/conditional/50
execute if score #execute aj.i matches 0 run function chica:animations/dining_area1/zzz/conditional/51