#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.chica.anim.door
execute if score .aj.anim_loop aj.chica.animating matches 0 run function chica:animation_loop
scoreboard players set #execute aj.i 1