#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/restrooms1/tree/left_hand_display_0-7
execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [67.3941f,3.9582f,92.9846f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [67.3941f,3.9582f,92.9846f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [67.3941f,3.9582f,92.9846f]