#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/restrooms1/tree/right_arm_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^-0.371 ^0.269 ^0 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.371 ^0.269 ^0 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.371 ^0.269 ^0 ~ ~