#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/restrooms1/tree/right_hand_display_0-7
execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [61.7402f,-13.2775f,-88.7192f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [61.7402f,-13.2775f,-88.7192f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [61.7402f,-13.2775f,-88.7192f]