#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function freddy:animations/show_stage/tree/eyelids_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^0 ^0.86 ^-0.025 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^0.86 ^-0.025 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^0.86 ^-0.025 ~ ~