#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function freddy:animations/show_stage/tree/left_hand_display_0-7
execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [8.5812f,64.7562f,103.3776f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [8.5812f,64.7562f,103.3776f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [8.5812f,64.7562f,103.3776f]