#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function freddy:animations/show_stage/tree/right_lower_leg_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^-0.194 ^-1.182 ^-0.075 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.194 ^-1.182 ^-0.075 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.194 ^-1.182 ^-0.075 ~ ~