#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function freddy:animations/show_stage/tree/right_hand_display_0-7
execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [48.5886f,-84.2201f,-131.8308f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [48.5886f,-84.2201f,-131.8308f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [48.5886f,-84.2201f,-131.8308f]