#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.backstage.normal.loopMode matches 0 run function backstage:animations/normal/stop
execute if score @s aj.backstage.normal.loopMode matches 1 run function backstage:animations/normal/pause
execute if score @s aj.backstage.normal.loopMode matches 2 run function backstage:animations/normal/zzz/execute/28