#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.backstage.root] run function backstage:animations/normal/zzz/conditional/18
execute if score #execute aj.i matches 0 run function backstage:animations/normal/zzz/conditional/19