#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,-12.5f,55f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [0f,-12.5f,55f]