#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/east_hall1/tree/pupils_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^0.023 ^0.825 ^0.056 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.023 ^0.825 ^0.056 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.023 ^0.825 ^0.056 ~ ~