#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[type=minecraft:area_effect_cloud] run function chica:animations/east_hall1/tree/root_bone_name
execute if entity @s[type=minecraft:armor_stand] run function chica:animations/east_hall1/tree/display_bone_name