#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/guitar/tree/eyelids_root_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/guitar/tree/eyelids_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0.001 ^0.893 ^0.07 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.001 ^0.907 ^0.045 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.001 ^0.918 ^0.018 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.001 ^0.933 ^-0.028 ~ ~