#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.001 ^0.943 ^-0.075 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.001 ^0.948 ^-0.113 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.001 ^0.949 ^-0.152 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.001 ^0.946 ^-0.191 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.001 ^0.947 ^-0.101 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.001 ^0.929 ^-0.012 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.001 ^0.893 ^0.07 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.001 ^0.907 ^0.045 ~ ~