#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/guitar/tree/eyes_root_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/guitar/tree/eyes_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0 ^0.832 ^0.128 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0 ^0.85 ^0.106 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0 ^0.865 ^0.083 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0 ^0.888 ^0.043 ~ ~