#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [90f,0f,-142.5f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [90f,0f,-136.25f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [90f,0f,-130f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [90f,0f,-135f]