#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/guitar/tree/guitar_display_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/guitar/tree/guitar_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [90f,0f,-140f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [90f,0f,-140f]