#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.306 ^0.543 ^0.788 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.322 ^0.565 ^0.788 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.338 ^0.587 ^0.788 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.334 ^0.553 ^0.788 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.331 ^0.518 ^0.788 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.331 ^0.549 ^0.788 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.331 ^0.581 ^0.788 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.331 ^0.556 ^0.788 ~ ~