#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [12.5f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [6.25f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-5f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-10f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-15f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-3.3333f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [8.3333f,0f,0f]