#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^0.587 ^-0.225 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^0.58 ^-0.232 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^0.572 ^-0.238 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^0.563 ^-0.243 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^0.582 ^-0.23 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^0.598 ^-0.212 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^0.61 ^-0.192 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^0.606 ^-0.199 ~ ~