#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/guitar/tree/jaw_root_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/guitar/tree/jaw_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0 ^0.61 ^-0.192 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0 ^0.606 ^-0.199 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0 ^0.603 ^-0.205 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0 ^0.595 ^-0.216 ~ ~