#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/guitar/tree/left_hand_display_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/guitar/tree/left_hand_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [89.0526f,41.4786f,-101.1082f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [82.7384f,42.9823f,-109.9911f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [76.7133f,46.0359f,-118.1705f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [84.005f,45.7757f,-108.3133f]