#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.156 ^1.625 ^-0.112 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.156 ^1.616 ^-0.26 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.156 ^1.584 ^-0.405 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.156 ^1.53 ^-0.541 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.156 ^1.624 ^-0.19 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.156 ^1.572 ^0.171 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.156 ^1.386 ^0.477 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.156 ^1.474 ^0.372 ~ ~