#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/guitar/tree/left_ear_display_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/guitar/tree/left_ear_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [47.5f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [36.875f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [26.25f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [13.125f,0f,0f]