#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.156 ^1.543 ^0.253 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.156 ^1.602 ^0.075 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.156 ^1.625 ^-0.112 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.156 ^1.613 ^-0.273 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.156 ^1.573 ^-0.428 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.156 ^1.507 ^-0.571 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.156 ^1.617 ^-0.234 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.156 ^1.591 ^0.124 ~ ~