#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.005 ^0.887 ^0.03 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.005 ^0.901 ^-0.004 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.005 ^0.911 ^-0.039 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.005 ^0.919 ^-0.075 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.005 ^0.896 ^0.008 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.005 ^0.858 ^0.083 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.005 ^0.805 ^0.15 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.005 ^0.823 ^0.13 ~ ~