#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.005 ^0.84 ^0.108 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.005 ^0.866 ^0.07 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.005 ^0.887 ^0.03 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.005 ^0.901 ^-0.004 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.005 ^0.911 ^-0.039 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.005 ^0.919 ^-0.075 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.005 ^0.896 ^0.008 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.005 ^0.858 ^0.083 ~ ~