#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/guitar/tree/right_ear_root_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/guitar/tree/right_ear_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^-0.162 ^1.129 ^0.116 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.162 ^1.145 ^0.075 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.162 ^1.158 ^0.033 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.162 ^1.173 ^-0.039 ~ ~