#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.162 ^1.542 ^0.255 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.162 ^1.602 ^0.076 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.162 ^1.625 ^-0.112 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.162 ^1.613 ^-0.274 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.162 ^1.572 ^-0.429 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.162 ^1.506 ^-0.573 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.162 ^1.617 ^-0.235 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.162 ^1.59 ^0.125 ~ ~