#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/guitar/tree/right_arm_display_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/guitar/tree/right_arm_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-13.7122f,-26.9462f,-51.6999f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-13.7122f,-26.9462f,-51.6999f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-13.7122f,-26.9462f,-51.6999f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-13.7122f,-26.9462f,-51.6999f]