#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/guitar/tree/right_hand_display_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/guitar/tree/right_hand_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [114.5972f,-63.506f,-123.3966f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [96.5912f,-64.7356f,-122.8416f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [78.5951f,-65.961f,-122.2887f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [89.0912f,-64.7356f,-122.8416f]