#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [99.5972f,-63.506f,-123.3966f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [89.0912f,-64.7356f,-122.8416f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [78.5951f,-65.961f,-122.2887f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [96.5912f,-64.7356f,-122.8416f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [114.5972f,-63.506f,-123.3966f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [95.9638f,-65.9651f,-122.1738f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [77.3569f,-68.4063f,-120.9458f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [95.9638f,-65.9651f,-122.1738f]