#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-59.2267f,-34.6943f,-48.7907f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-59.2267f,-34.6943f,-48.7907f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-59.2267f,-34.6943f,-48.7907f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-59.2267f,-34.6943f,-48.7907f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-59.2267f,-34.6943f,-48.7907f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-59.2267f,-34.6943f,-48.7907f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-59.2267f,-34.6943f,-48.7907f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-59.2267f,-34.6943f,-48.7907f]