#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function foxy:animations/stage_2/tree/right_lower_leg_root_0-7
execute if score .this aj.frame matches 8..15 run function foxy:animations/stage_2/tree/right_lower_leg_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^-0.156 ^-1.275 ^0 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.156 ^-1.275 ^0 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.156 ^-1.275 ^0 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.156 ^-1.275 ^0 ~ ~