#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function foxy:animations/stage_2/tree/right_hand_display_0-7
execute if score .this aj.frame matches 8..15 run function foxy:animations/stage_2/tree/right_hand_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [156.145f,-11.5736f,75.708f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [156.145f,-11.5736f,75.708f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [156.145f,-11.5736f,75.708f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [156.145f,-11.5736f,75.708f]