#Project generated by Animated Java (https://animated-java.dev/)

tag @s remove aj.door_right.anim.close
tag @s remove aj.door_right.anim.open
scoreboard players set @s aj.frame 0
scoreboard players operation .this aj.id = @s aj.id
execute as @e[type=minecraft:area_effect_cloud,tag=aj.door_right.bone,distance=..6.251] if score @s aj.id = .this aj.id run function door_right:zzz/execute/8
execute as @e[type=minecraft:armor_stand,tag=aj.door_right.bone,distance=..6.251] if score @s aj.id = .this aj.id run function door_right:zzz/execute/9
scoreboard players set #execute aj.i 1