#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.freddy.anim.e_hall_corner
execute if score .aj.anim_loop aj.freddy.animating matches 0 run function freddy:animation_loop
scoreboard players set #execute aj.i 1