#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [38.125f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [40f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [40.8333f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [41.6667f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [42.5f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [43.3333f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [44.1667f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [45f,0f,0f]