#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.142 ^0.674 ^0.784 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.009 ^0.676 ^0.805 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.126 ^0.658 ^0.776 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.146 ^0.641 ^0.919 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.166 ^0.623 ^1.061 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.001 ^0.635 ^1.231 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.163 ^0.596 ^1.363 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.163 ^0.583 ^1.507 ~ ~