#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.125 ^0.622 ^0.769 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.008 ^0.622 ^0.791 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.111 ^0.604 ^0.767 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.129 ^0.588 ^0.91 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.146 ^0.571 ^1.051 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.001 ^0.58 ^1.217 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.144 ^0.545 ^1.35 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.144 ^0.532 ^1.493 ~ ~