#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^0.232 ^0.657 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^0.21 ^0.687 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^0.199 ^0.701 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^0.189 ^0.839 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^0.179 ^0.977 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^0.168 ^1.114 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^0.157 ^1.252 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^0.146 ^1.39 ~ ~