#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-0.744 ^1.145 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^-0.496 ^1.126 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^-0.257 ^1.053 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^-0.039 ^0.931 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^0.146 ^0.765 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^0.291 ^0.562 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^0.273 ^0.594 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^0.253 ^0.626 ~ ~