#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [15.3099f,-1.8859f,17.2782f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [14.1195f,1.0435f,1.3159f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [9.0661f,4.8078f,-14.5651f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [9.6738f,5.4485f,-16.9711f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [10.1967f,6.1317f,-19.3649f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [14.04f,2.1641f,0.3703f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [13.3156f,-2.3612f,19.846f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [14.1003f,-2.6439f,19.8118f]