#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.035 ^0.343 ^0.657 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.003 ^0.326 ^0.684 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.028 ^0.312 ^0.687 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.033 ^0.301 ^0.827 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.037 ^0.289 ^0.966 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.001 ^0.285 ^1.111 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.039 ^0.267 ^1.248 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.039 ^0.256 ^1.387 ~ ~