#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [142.5f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [87.5f,0f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [45f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [44.375f,0f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [18.6093f,-2.2494f,7.1566f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [15.5909f,-0.2203f,9.9362f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [26.7702f,-0.1811f,12.3957f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [21.0902f,-0.9652f,14.8571f]