#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [118.1692f,-43.4166f,-33.741f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [82.9268f,-46.4884f,-14.5469f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [47.7177f,-43.4902f,3.9421f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [16.6659f,-35.7384f,17.346f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-5.602f,-21.9589f,21.1774f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-25.9295f,-8.6018f,19.9263f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-24.1436f,-9.2367f,19.6494f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-22.3513f,-9.8626f,19.352f]