#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.869 ^-0.041 ^0.451 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.869 ^-0.056 ^0.473 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.869 ^-0.063 ^0.482 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.869 ^-0.07 ^0.617 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.869 ^-0.077 ^0.751 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.869 ^-0.084 ^0.885 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.869 ^-0.092 ^1.019 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.869 ^-0.099 ^1.153 ~ ~