#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.356 ^-0.713 ^1.003 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.356 ^-0.496 ^0.981 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.356 ^-0.288 ^0.912 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.356 ^-0.101 ^0.8 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.356 ^0.058 ^0.65 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.356 ^0.18 ^0.469 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.356 ^0.164 ^0.498 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.356 ^0.148 ^0.526 ~ ~