#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [71.952f,-44.7865f,38.3409f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [42.1056f,-15.423f,43.4424f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [14.7964f,12.296f,39.3756f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-17.5437f,35.715f,25.7587f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-36.6296f,50.6571f,-3.1753f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-65.0725f,49.5972f,-42.3375f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-62.8776f,50.8397f,-40.6505f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-60.5647f,52.0388f,-38.8418f]