#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-20.5523f,-10.4791f,19.0343f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-18.7461f,-11.0854f,18.6964f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-17.941f,-11.3515f,18.5398f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-17.1344f,-11.6153f,18.3792f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-16.3263f,-11.8769f,18.2146f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-15.5166f,-12.1363f,18.0462f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-14.7054f,-12.3932f,17.8739f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-13.8925f,-12.6478f,17.6977f]