#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.693 ^-0.491 ^0.629 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.727 ^-0.399 ^0.586 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.758 ^-0.312 ^0.537 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.785 ^-0.229 ^0.48 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.834 ^-0.121 ^0.443 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.869 ^0 ^0.384 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.869 ^-0.013 ^0.407 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.869 ^-0.026 ^0.429 ~ ~