#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-1.096 ^1.415 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^-0.476 ^1.569 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^0.117 ^1.292 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.002 ^0.334 ^1.147 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.049 ^0.562 ^0.782 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.064 ^0.692 ^0.544 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.086 ^0.692 ^0.645 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.102 ^0.67 ^0.71 ~ ~