#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.119 ^0.643 ^0.774 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.002 ^0.634 ^0.794 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.113 ^0.61 ^0.768 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.125 ^0.596 ^0.911 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.137 ^0.581 ^1.054 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.001 ^0.586 ^1.219 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.135 ^0.555 ^1.352 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.135 ^0.542 ^1.495 ~ ~