#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-23.8709f,-1.5461f,2.572f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-21.997f,-1.6294f,2.52f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-21.1641f,-1.6659f,2.4961f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-20.3312f,-1.702f,2.4716f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-19.4983f,-1.7378f,2.4466f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-18.6653f,-1.7732f,2.4211f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-17.8323f,-1.8082f,2.3951f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-16.9993f,-1.8428f,2.3685f]