#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-35.51f,-45.8571f,29.0027f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-33.1168f,-46.7415f,27.2723f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-32.0283f,-47.1182f,26.4771f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-30.9245f,-47.4845f,25.6659f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-29.8054f,-47.84f,24.8386f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-28.6711f,-48.1845f,23.9955f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-27.5217f,-48.5177f,23.1367f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-26.3574f,-48.8393f,22.2622f]