#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [74.3735f,48.3239f,-24.7126f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [49.5669f,20.973f,-38.4376f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [33.3699f,-8.6135f,-37.7787f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [13.189f,-35.9948f,-24.6565f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-11.8833f,-45.1766f,3.7333f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-42.2333f,-42.9259f,33.7103f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-40.0668f,-43.9463f,32.2206f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-37.8263f,-44.9244f,30.6518f]