#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.door_right.bone.wall] run function door_right:animations/open/tree/wall_root_top
execute if entity @s[tag=aj.door_right.bone.door] run function door_right:animations/open/tree/door_root_top
execute store result entity @s Air short 1 run scoreboard players get .this aj.frame