#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function door_right:animations/open/tree/wall_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^0 ^-1.813 ^0 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^-1.813 ^0 ~ ~