#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.chica.restrooms1.loopMode matches 0 run function chica:animations/restrooms1/stop
execute if score @s aj.chica.restrooms1.loopMode matches 1 run function chica:animations/restrooms1/pause
execute if score @s aj.chica.restrooms1.loopMode matches 2 run function chica:animations/restrooms1/zzz/execute/103