#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^0.237 ^-0.094 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^0.237 ^-0.094 ~ ~