#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.906 ^-2.263 ^-0.081 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.906 ^-2.263 ^-0.081 ~ ~