#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.194 ^-2.338 ^-0.075 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.194 ^-2.338 ^-0.075 ~ ~