#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.bonnie.supply_closet.loopMode matches 0 run function bonnie:animations/supply_closet/stop
execute if score @s aj.bonnie.supply_closet.loopMode matches 1 run function bonnie:animations/supply_closet/pause
execute if score @s aj.bonnie.supply_closet.loopMode matches 2 run function bonnie:animations/supply_closet/zzz/execute/137