#Project generated by Animated Java (https://animated-java.dev/)

summon minecraft:marker ~ ~ ~ {Tags:['right_door','new','aj.door_right','aj.door_right.root']}
execute as @e[type=minecraft:marker,tag=aj.door_right.root,tag=new,distance=..1,limit=1] rotated ~ 0 run function door_right:summon/zzz/execute/2
function door_right:assert_animation_flags