#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.right_door.root] at @s run function right_door:set_variant/zzz/conditional/4
execute if score #execute aj.i matches 0 run function right_door:set_variant/zzz/conditional/5