#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.bonnie.jumpscare.loopMode matches 0 run function bonnie:animations/jumpscare/stop
execute if score @s aj.bonnie.jumpscare.loopMode matches 1 run function bonnie:animations/jumpscare/pause
execute if score @s aj.bonnie.jumpscare.loopMode matches 2 run function bonnie:animations/jumpscare/zzz/execute/141