#Project generated by Animated Java (https://animated-java.dev/)

summon minecraft:marker ~ ~ ~ {Tags:['right_door','new','aj.right_door','aj.right_door.root']}
execute as @e[type=minecraft:marker,tag=aj.right_door.root,tag=new,distance=..1,limit=1] rotated ~ 0 run function right_door:summon/zzz/execute/2
function right_door:assert_animation_flags