#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.bonnie.dining_area.loopMode matches 0 run function bonnie:animations/dining_area/stop
execute if score @s aj.bonnie.dining_area.loopMode matches 1 run function bonnie:animations/dining_area/pause
execute if score @s aj.bonnie.dining_area.loopMode matches 2 run function bonnie:animations/dining_area/zzz/execute/134