#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.chica.bone.left_leg] ArmorItems[-1].tag.CustomModelData set value 495
data modify entity @s[tag=aj.chica.bone.left_lower_leg] ArmorItems[-1].tag.CustomModelData set value 496
data modify entity @s[tag=aj.chica.bone.right_leg] ArmorItems[-1].tag.CustomModelData set value 497
data modify entity @s[tag=aj.chica.bone.right_lower_leg] ArmorItems[-1].tag.CustomModelData set value 498
data modify entity @s[tag=aj.chica.bone.body] ArmorItems[-1].tag.CustomModelData set value 499
data modify entity @s[tag=aj.chica.bone.head] ArmorItems[-1].tag.CustomModelData set value 500
data modify entity @s[tag=aj.chica.bone.jaw] ArmorItems[-1].tag.CustomModelData set value 501
data modify entity @s[tag=aj.chica.bone.eyes] ArmorItems[-1].tag.CustomModelData set value 502
data modify entity @s[tag=aj.chica.bone.pupils] ArmorItems[-1].tag.CustomModelData set value 503
data modify entity @s[tag=aj.chica.bone.right_arm] ArmorItems[-1].tag.CustomModelData set value 504
data modify entity @s[tag=aj.chica.bone.right_hand] ArmorItems[-1].tag.CustomModelData set value 505
data modify entity @s[tag=aj.chica.bone.left_arm] ArmorItems[-1].tag.CustomModelData set value 506
data modify entity @s[tag=aj.chica.bone.left_hand] ArmorItems[-1].tag.CustomModelData set value 507
data modify entity @s[tag=aj.chica.bone.eyelids] ArmorItems[-1].tag.CustomModelData set value 489