#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.chica.bone.left_leg] ArmorItems[-1].tag.CustomModelData set value 549
data modify entity @s[tag=aj.chica.bone.left_lower_leg] ArmorItems[-1].tag.CustomModelData set value 550
data modify entity @s[tag=aj.chica.bone.right_leg] ArmorItems[-1].tag.CustomModelData set value 551
data modify entity @s[tag=aj.chica.bone.right_lower_leg] ArmorItems[-1].tag.CustomModelData set value 552
data modify entity @s[tag=aj.chica.bone.body] ArmorItems[-1].tag.CustomModelData set value 553
data modify entity @s[tag=aj.chica.bone.head] ArmorItems[-1].tag.CustomModelData set value 554
data modify entity @s[tag=aj.chica.bone.jaw] ArmorItems[-1].tag.CustomModelData set value 555
data modify entity @s[tag=aj.chica.bone.eyes] ArmorItems[-1].tag.CustomModelData set value 556
data modify entity @s[tag=aj.chica.bone.pupils] ArmorItems[-1].tag.CustomModelData set value 558
data modify entity @s[tag=aj.chica.bone.right_arm] ArmorItems[-1].tag.CustomModelData set value 559
data modify entity @s[tag=aj.chica.bone.right_hand] ArmorItems[-1].tag.CustomModelData set value 560
data modify entity @s[tag=aj.chica.bone.left_arm] ArmorItems[-1].tag.CustomModelData set value 561
data modify entity @s[tag=aj.chica.bone.left_hand] ArmorItems[-1].tag.CustomModelData set value 562
data modify entity @s[tag=aj.chica.bone.eyelids] ArmorItems[-1].tag.CustomModelData set value 557