#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.chica.bone.left_leg] ArmorItems[-1].tag.CustomModelData set value 577
data modify entity @s[tag=aj.chica.bone.left_lower_leg] ArmorItems[-1].tag.CustomModelData set value 578
data modify entity @s[tag=aj.chica.bone.right_leg] ArmorItems[-1].tag.CustomModelData set value 579
data modify entity @s[tag=aj.chica.bone.right_lower_leg] ArmorItems[-1].tag.CustomModelData set value 580
data modify entity @s[tag=aj.chica.bone.body] ArmorItems[-1].tag.CustomModelData set value 581
data modify entity @s[tag=aj.chica.bone.head] ArmorItems[-1].tag.CustomModelData set value 582
data modify entity @s[tag=aj.chica.bone.jaw] ArmorItems[-1].tag.CustomModelData set value 583
data modify entity @s[tag=aj.chica.bone.eyes] ArmorItems[-1].tag.CustomModelData set value 584
data modify entity @s[tag=aj.chica.bone.pupils] ArmorItems[-1].tag.CustomModelData set value 586
data modify entity @s[tag=aj.chica.bone.right_arm] ArmorItems[-1].tag.CustomModelData set value 587
data modify entity @s[tag=aj.chica.bone.right_hand] ArmorItems[-1].tag.CustomModelData set value 588
data modify entity @s[tag=aj.chica.bone.left_arm] ArmorItems[-1].tag.CustomModelData set value 589
data modify entity @s[tag=aj.chica.bone.left_hand] ArmorItems[-1].tag.CustomModelData set value 590
data modify entity @s[tag=aj.chica.bone.eyelids] ArmorItems[-1].tag.CustomModelData set value 585