#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.chica.bone.left_leg] ArmorItems[-1].tag.CustomModelData set value 591
data modify entity @s[tag=aj.chica.bone.left_lower_leg] ArmorItems[-1].tag.CustomModelData set value 592
data modify entity @s[tag=aj.chica.bone.right_leg] ArmorItems[-1].tag.CustomModelData set value 593
data modify entity @s[tag=aj.chica.bone.right_lower_leg] ArmorItems[-1].tag.CustomModelData set value 594
data modify entity @s[tag=aj.chica.bone.body] ArmorItems[-1].tag.CustomModelData set value 595
data modify entity @s[tag=aj.chica.bone.head] ArmorItems[-1].tag.CustomModelData set value 596
data modify entity @s[tag=aj.chica.bone.jaw] ArmorItems[-1].tag.CustomModelData set value 597
data modify entity @s[tag=aj.chica.bone.eyes] ArmorItems[-1].tag.CustomModelData set value 598
data modify entity @s[tag=aj.chica.bone.pupils] ArmorItems[-1].tag.CustomModelData set value 600
data modify entity @s[tag=aj.chica.bone.right_arm] ArmorItems[-1].tag.CustomModelData set value 601
data modify entity @s[tag=aj.chica.bone.right_hand] ArmorItems[-1].tag.CustomModelData set value 602
data modify entity @s[tag=aj.chica.bone.left_arm] ArmorItems[-1].tag.CustomModelData set value 603
data modify entity @s[tag=aj.chica.bone.left_hand] ArmorItems[-1].tag.CustomModelData set value 604
data modify entity @s[tag=aj.chica.bone.eyelids] ArmorItems[-1].tag.CustomModelData set value 599