#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.chica.bone.left_leg] ArmorItems[-1].tag.CustomModelData set value 1004
data modify entity @s[tag=aj.chica.bone.left_lower_leg] ArmorItems[-1].tag.CustomModelData set value 1005
data modify entity @s[tag=aj.chica.bone.right_leg] ArmorItems[-1].tag.CustomModelData set value 1006
data modify entity @s[tag=aj.chica.bone.right_lower_leg] ArmorItems[-1].tag.CustomModelData set value 1007
data modify entity @s[tag=aj.chica.bone.body] ArmorItems[-1].tag.CustomModelData set value 1008
data modify entity @s[tag=aj.chica.bone.head] ArmorItems[-1].tag.CustomModelData set value 1009
data modify entity @s[tag=aj.chica.bone.jaw] ArmorItems[-1].tag.CustomModelData set value 1010
data modify entity @s[tag=aj.chica.bone.eyes] ArmorItems[-1].tag.CustomModelData set value 1011
data modify entity @s[tag=aj.chica.bone.pupils] ArmorItems[-1].tag.CustomModelData set value 1013
data modify entity @s[tag=aj.chica.bone.right_arm] ArmorItems[-1].tag.CustomModelData set value 1014
data modify entity @s[tag=aj.chica.bone.right_hand] ArmorItems[-1].tag.CustomModelData set value 1015
data modify entity @s[tag=aj.chica.bone.left_arm] ArmorItems[-1].tag.CustomModelData set value 1016
data modify entity @s[tag=aj.chica.bone.left_hand] ArmorItems[-1].tag.CustomModelData set value 1017
data modify entity @s[tag=aj.chica.bone.eyelids] ArmorItems[-1].tag.CustomModelData set value 1012