#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/door/tree/body_display_0-7
execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [15.228f,12.3273f,1.3231f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [15.228f,12.3273f,1.3231f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [15.228f,12.3273f,1.3231f]