#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [15.228f,12.3273f,1.3231f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [15.228f,12.3273f,1.3231f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [15.228f,12.3273f,1.3231f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [15.228f,12.3273f,1.3231f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [15.228f,12.3273f,1.3231f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [15.228f,12.3273f,1.3231f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [15.228f,12.3273f,1.3231f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [15.228f,12.3273f,1.3231f]