#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/door/tree/jaw_display_0-7
execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [27.4816f,52.584f,18.304f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [27.4816f,52.584f,18.304f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [27.4816f,52.584f,18.304f]