#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/door/tree/left_arm_display_0-7
execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [18.3792f,-6.6312f,58.595f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [18.3792f,-6.6312f,58.595f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [18.3792f,-6.6312f,58.595f]