#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/door/tree/left_hand_display_0-7
execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [12.7614f,-14.8687f,87.9969f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [12.7614f,-14.8687f,87.9969f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [12.7614f,-14.8687f,87.9969f]