#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/door/tree/right_upper_ear_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^-0.023 ^1.606 ^0.233 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.023 ^1.606 ^0.233 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.023 ^1.606 ^0.233 ~ ~