#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.bonnie.bone.head] run function bonnie:animations/door/tree/head_root_top
execute if entity @s[tag=aj.bonnie.bone.eyes] run function bonnie:animations/door/tree/eyes_root_top
execute if entity @s[tag=aj.bonnie.bone.left_ear] run function bonnie:animations/door/tree/left_ear_root_top
execute if entity @s[tag=aj.bonnie.bone.right_ear] run function bonnie:animations/door/tree/right_ear_root_top
execute if entity @s[tag=aj.bonnie.bone.left_upper_ear] run function bonnie:animations/door/tree/left_upper_ear_root_top
execute if entity @s[tag=aj.bonnie.bone.right_upper_ear] run function bonnie:animations/door/tree/right_upper_ear_root_top
execute if entity @s[tag=aj.bonnie.bone.jaw] run function bonnie:animations/door/tree/jaw_root_top
execute if entity @s[tag=aj.bonnie.bone.body] run function bonnie:animations/door/tree/body_root_top
execute if entity @s[tag=aj.bonnie.bone.left_arm] run function bonnie:animations/door/tree/left_arm_root_top
execute if entity @s[tag=aj.bonnie.bone.left_hand] run function bonnie:animations/door/tree/left_hand_root_top
execute if entity @s[tag=aj.bonnie.bone.right_hand] run function bonnie:animations/door/tree/right_hand_root_top
execute if entity @s[tag=aj.bonnie.bone.right_arm] run function bonnie:animations/door/tree/right_arm_root_top
execute if entity @s[tag=aj.bonnie.bone.left_leg] run function bonnie:animations/door/tree/left_leg_root_top
execute if entity @s[tag=aj.bonnie.bone.left_lower_leg] run function bonnie:animations/door/tree/left_lower_leg_root_top
execute if entity @s[tag=aj.bonnie.bone.right_leg] run function bonnie:animations/door/tree/right_leg_root_top
execute if entity @s[tag=aj.bonnie.bone.right_lower_leg] run function bonnie:animations/door/tree/right_lower_leg_root_top
execute if entity @s[tag=aj.bonnie.bone.pupils] run function bonnie:animations/door/tree/pupils_root_top
execute if entity @s[tag=aj.bonnie.bone.eyelids] run function bonnie:animations/door/tree/eyelids_root_top
execute if entity @s[tag=aj.bonnie.bone.guitar] run function bonnie:animations/door/tree/guitar_root_top
execute store result entity @s Air short 1 run scoreboard players get .this aj.frame