#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [0f,0f,3f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [0f,0f,6f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [0f,0f,9f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [0f,0f,12f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [0f,0f,15f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [0f,0f,18f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [0f,0f,21f]