#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-0.625 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.068 ^-0.625 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.162 ^-0.625 ^0 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.274 ^-0.625 ^0 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.4 ^-0.625 ^0 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.531 ^-0.625 ^0 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.663 ^-0.625 ^0 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.788 ^-0.625 ^0 ~ ~