#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [0f,0f,24f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [0f,0f,27f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [0f,0f,30f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [0f,0f,27.5f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [0f,0f,25f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [0f,0f,27.5f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [0f,0f,30f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [0f,0f,27.5f]