#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.116 ^0.977 ^0.233 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.036 ^0.981 ^0.233 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.213 ^0.98 ^0.233 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.41 ^0.975 ^0.233 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.617 ^0.964 ^0.238 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.829 ^0.948 ^0.243 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^1.041 ^0.929 ^0.247 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^1.246 ^0.905 ^0.251 ~ ~