#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^1.437 ^0.878 ^0.254 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^1.607 ^0.847 ^0.256 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^1.751 ^0.812 ^0.258 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^1.653 ^0.843 ^0.27 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^1.554 ^0.865 ^0.282 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^1.653 ^0.843 ^0.27 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^1.751 ^0.812 ^0.258 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^1.642 ^0.842 ^0.274 ~ ~