#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [112.5f,-14.2857f,16.8571f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [112.5f,-17.1429f,18.4286f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [112.5f,-20f,20f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [67.61f,-19.9108f,13.5123f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [22.7199f,-19.8217f,7.0247f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [21.36f,-19.9108f,13.5123f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [20f,-20f,20f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [21.8169f,-19.9207f,12.1809f]