#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function foxy:animations/jumpscare/tree/eyepatch_root_0-7
execute if score .this aj.frame matches 8..15 run function foxy:animations/jumpscare/tree/eyepatch_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^1.813 ^0.781 ^0.258 ~ ~