#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^1.333 ^0.345 ^0 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^1.477 ^0.321 ^0 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^1.594 ^0.295 ^0 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^1.553 ^0.317 ^0 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^1.512 ^0.337 ^0 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^1.553 ^0.317 ^0 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^1.594 ^0.295 ^0 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^1.553 ^0.317 ^0 ~ ~