#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [0f,0f,3f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [0f,0f,6f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [0f,0f,9f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [0f,-2.8571f,10.5714f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [0f,-5.7143f,12.1429f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [0f,-8.5714f,13.7143f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [0f,-11.4286f,15.2857f]