#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^0.437 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.124 ^0.436 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.273 ^0.431 ^0 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.44 ^0.424 ^0 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.62 ^0.414 ^0 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.806 ^0.401 ^0 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.991 ^0.385 ^0 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^1.169 ^0.366 ^0 ~ ~