#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^1.377 ^0.489 ^0 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^1.524 ^0.464 ^0 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^1.645 ^0.436 ^0 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^1.589 ^0.462 ^0.003 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^1.532 ^0.486 ^0.007 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^1.589 ^0.462 ^0.003 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^1.645 ^0.436 ^0 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^1.586 ^0.463 ^0.004 ~ ~