#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^0.587 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.131 ^0.585 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.288 ^0.58 ^0 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.464 ^0.572 ^0 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.648 ^0.561 ^0 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.838 ^0.547 ^0 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^1.027 ^0.531 ^0 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^1.209 ^0.511 ^0 ~ ~