#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,70f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [0f,0f,71f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [0f,0f,72f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [0f,0f,73f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [0f,0f,74f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [0f,0f,75f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [0f,0f,76f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [0f,0f,77f]