#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.15 ^-0.65 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.218 ^-0.65 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.312 ^-0.65 ^0 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.424 ^-0.65 ^0 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.55 ^-0.65 ^0 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.681 ^-0.65 ^0 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.813 ^-0.65 ^0 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.938 ^-0.65 ^0 ~ ~