#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^1.582 ^0.043 ^0 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^1.709 ^0.006 ^0 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^1.809 ^-0.032 ^0 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^1.783 ^0 ^0 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^1.755 ^0.031 ^0 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^1.783 ^0 ^0 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^1.809 ^-0.032 ^0 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^1.783 ^0 ^0 ~ ~