#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.35 ^0.262 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.464 ^0.242 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.602 ^0.221 ^0 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.759 ^0.196 ^0 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.926 ^0.17 ^0 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^1.099 ^0.141 ^0 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^1.27 ^0.11 ^0 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^1.433 ^0.078 ^0 ~ ~