#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function foxy:animations/jumpscare/tree/left_lower_leg_root_0-7
execute if score .this aj.frame matches 8..15 run function foxy:animations/jumpscare/tree/left_lower_leg_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^1.215 ^-1.273 ^0.004 ~ ~