#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.153 ^-1.273 ^0.004 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.221 ^-1.273 ^0.004 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.314 ^-1.273 ^0.004 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.427 ^-1.273 ^0.004 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.552 ^-1.273 ^0.004 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.684 ^-1.273 ^0.004 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.816 ^-1.273 ^0.004 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.941 ^-1.273 ^0.004 ~ ~