#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,12.5f,87.5f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [0.3814f,12.4413f,90.2898f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [0.7628f,12.3826f,93.0796f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [1.1442f,12.3238f,95.8694f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [1.5256f,12.2651f,98.6592f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [1.907f,12.2064f,101.449f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [2.2884f,12.1477f,104.2388f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [2.6698f,12.0889f,107.0287f]