#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.156 ^-0.65 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.088 ^-0.65 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.005 ^-0.65 ^0 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.118 ^-0.65 ^0 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.243 ^-0.65 ^0 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.375 ^-0.65 ^0 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.507 ^-0.65 ^0 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.632 ^-0.65 ^0 ~ ~