#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.35 ^0.262 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.235 ^0.279 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.094 ^0.294 ^0 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.067 ^0.306 ^0 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.242 ^0.315 ^0 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.423 ^0.322 ^0 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.604 ^0.327 ^0 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.78 ^0.328 ^0 ~ ~