#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,-15f,-85f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [0f,-15f,-82f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [0f,-15f,-79f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [0f,-15f,-76f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [0f,-15f,-73f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [0f,-15f,-70f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [0f,-15f,-67f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [0f,-15f,-64f]