#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.156 ^-1.275 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.088 ^-1.275 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.005 ^-1.275 ^0 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.118 ^-1.275 ^0 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.243 ^-1.275 ^0 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.375 ^-1.275 ^0 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.507 ^-1.275 ^0 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.632 ^-1.275 ^0 ~ ~