#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.942 ^0.328 ^0 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^1.086 ^0.324 ^0 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^1.203 ^0.318 ^0 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^1.162 ^0.323 ^0 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^1.12 ^0.327 ^0 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^1.162 ^0.323 ^0 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^1.203 ^0.318 ^0 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^1.162 ^0.323 ^0 ~ ~