#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.chica.bone.body] run function chica:animations/e_hall_corner_twitching/tree/body_display_top
execute if entity @s[tag=aj.chica.bone.left_arm] run function chica:animations/e_hall_corner_twitching/tree/left_arm_display_top
execute if entity @s[tag=aj.chica.bone.left_hand] run function chica:animations/e_hall_corner_twitching/tree/left_hand_display_top
execute if entity @s[tag=aj.chica.bone.right_hand] run function chica:animations/e_hall_corner_twitching/tree/right_hand_display_top
execute if entity @s[tag=aj.chica.bone.right_arm] run function chica:animations/e_hall_corner_twitching/tree/right_arm_display_top
execute if entity @s[tag=aj.chica.bone.left_leg] run function chica:animations/e_hall_corner_twitching/tree/left_leg_display_top
execute if entity @s[tag=aj.chica.bone.left_lower_leg] run function chica:animations/e_hall_corner_twitching/tree/left_lower_leg_display_top
execute if entity @s[tag=aj.chica.bone.right_leg] run function chica:animations/e_hall_corner_twitching/tree/right_leg_display_top
execute if entity @s[tag=aj.chica.bone.right_lower_leg] run function chica:animations/e_hall_corner_twitching/tree/right_lower_leg_display_top
execute if entity @s[tag=aj.chica.bone.head] run function chica:animations/e_hall_corner_twitching/tree/head_display_top
execute if entity @s[tag=aj.chica.bone.jaw] run function chica:animations/e_hall_corner_twitching/tree/jaw_display_top
execute if entity @s[tag=aj.chica.bone.eyes] run function chica:animations/e_hall_corner_twitching/tree/eyes_display_top
execute if entity @s[tag=aj.chica.bone.pupils] run function chica:animations/e_hall_corner_twitching/tree/pupils_display_top
execute if entity @s[tag=aj.chica.bone.eyelids] run function chica:animations/e_hall_corner_twitching/tree/eyelids_display_top
execute positioned as @s run tp @s ~ ~ ~ ~ ~