#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/e_hall_corner_twitching/tree/eyelids_root_0-7
execute if score .this aj.frame matches 8..15 run function chica:animations/e_hall_corner_twitching/tree/eyelids_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^-0.192 ^0.831 ^-0.084 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.192 ^0.831 ^-0.084 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.065 ^0.871 ^0.003 ~ ~