#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.065 ^0.871 ^0.003 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.182 ^0.843 ^-0.021 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.182 ^0.843 ^-0.021 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.182 ^0.843 ^-0.021 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.065 ^0.871 ^0.003 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.065 ^0.871 ^0.003 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.065 ^0.871 ^0.003 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.192 ^0.831 ^-0.084 ~ ~