#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/e_hall_corner_twitching/tree/jaw_root_0-7
execute if score .this aj.frame matches 8..15 run function chica:animations/e_hall_corner_twitching/tree/jaw_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0.018 ^0.557 ^0.07 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.018 ^0.557 ^0.07 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.068 ^0.525 ^0.1 ~ ~