#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-6.8169f,-19.9207f,5.3191f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-10.203f,-22.5521f,22.1206f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-10.203f,-22.5521f,22.1206f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-10.203f,-22.5521f,22.1206f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-6.8169f,-19.9207f,5.3191f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-6.8169f,-19.9207f,5.3191f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-6.8169f,-19.9207f,5.3191f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [33.248f,-31.8674f,-21.2782f]