#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/e_hall_corner_twitching/tree/left_eyebrow_display_0-7
execute if score .this aj.frame matches 8..15 run function chica:animations/e_hall_corner_twitching/tree/left_eyebrow_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-19.252f,-31.8674f,-21.2782f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-19.252f,-31.8674f,-21.2782f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-6.8169f,-19.9207f,5.3191f]