#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.215 ^0.581 ^0.055 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.337 ^0.516 ^0.022 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.337 ^0.516 ^0.022 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.337 ^0.516 ^0.022 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.215 ^0.581 ^0.055 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.215 ^0.581 ^0.055 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.215 ^0.581 ^0.055 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.062 ^0.606 ^-0.065 ~ ~