#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.215 ^0.581 ^0.055 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.215 ^0.581 ^0.055 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.215 ^0.581 ^0.055 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.337 ^0.516 ^0.022 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.337 ^0.516 ^0.022 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.337 ^0.516 ^0.022 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.215 ^0.581 ^0.055 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.215 ^0.581 ^0.055 ~ ~