#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.063 ^0.833 ^0.007 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.063 ^0.833 ^0.007 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.063 ^0.833 ^0.007 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.16 ^0.812 ^-0.01 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.16 ^0.812 ^-0.01 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.16 ^0.812 ^-0.01 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.063 ^0.833 ^0.007 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.063 ^0.833 ^0.007 ~ ~