#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/e_hall_corner_twitching/tree/pupils_root_0-7
execute if score .this aj.frame matches 8..15 run function chica:animations/e_hall_corner_twitching/tree/pupils_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^-0.166 ^0.79 ^-0.07 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.166 ^0.79 ^-0.07 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.063 ^0.833 ^0.007 ~ ~