#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/e_hall_corner_twitching/tree/right_eyebrow_root_0-7
execute if score .this aj.frame matches 8..15 run function chica:animations/e_hall_corner_twitching/tree/right_eyebrow_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^-0.241 ^0.536 ^0.053 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.241 ^0.536 ^0.053 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.005 ^0.601 ^0.132 ~ ~