#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/restrooms2/tree/left_lower_leg_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^0.269 ^-1.032 ^-0.062 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.269 ^-1.032 ^-0.062 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.269 ^-1.032 ^-0.062 ~ ~