#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/restrooms2/tree/left_arm_display_0-7
execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [1.1069f,-12.4517f,64.8792f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [1.1069f,-12.4517f,64.8792f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [1.1069f,-12.4517f,64.8792f]