#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.67 ^-0.273 ^-0.188 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.67 ^-0.273 ^-0.188 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.67 ^-0.273 ^-0.188 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.67 ^-0.273 ^-0.188 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.67 ^-0.273 ^-0.188 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.67 ^-0.273 ^-0.188 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.67 ^-0.273 ^-0.188 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.67 ^-0.273 ^-0.188 ~ ~