#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/restrooms2/tree/left_hand_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^0.67 ^-0.273 ^-0.188 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.67 ^-0.273 ^-0.188 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.67 ^-0.273 ^-0.188 ~ ~