#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [-1.3184f,9.9136f,-70.1144f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-1.3184f,9.9136f,-70.1144f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-1.3184f,9.9136f,-70.1144f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-1.3184f,9.9136f,-70.1144f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-1.3184f,9.9136f,-70.1144f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-1.3184f,9.9136f,-70.1144f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-1.3184f,9.9136f,-70.1144f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-1.3184f,9.9136f,-70.1144f]