#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/restrooms2/tree/right_lower_leg_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^-0.222 ^-1.029 ^-0.062 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.222 ^-1.029 ^-0.062 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.222 ^-1.029 ^-0.062 ~ ~