#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.001 ^0.936 ^-0.037 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.056 ^0.932 ^-0.037 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.001 ^0.936 ^-0.037 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.001 ^0.936 ^-0.037 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.001 ^0.936 ^-0.037 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.16 ^0.987 ^-0.064 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.16 ^0.987 ^-0.064 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.16 ^0.987 ^-0.064 ~ ~