#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^0.892 ^0.034 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.052 ^0.888 ^0.034 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^0.892 ^0.034 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^0.892 ^0.034 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^0.892 ^0.034 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.107 ^0.971 ^0.003 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.107 ^0.971 ^0.003 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.107 ^0.971 ^0.003 ~ ~