#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/w_hall_corner_twitching/tree/jaw_root_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/w_hall_corner_twitching/tree/jaw_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0 ^0.594 ^-0.218 ~ ~