#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/w_hall_corner_twitching/tree/left_leg_root_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/w_hall_corner_twitching/tree/left_leg_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0.2 ^-0.694 ^-0.062 ~ ~