#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [22.5f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [22.5f,0f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [22.4574f,0.6518f,-7.4718f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [22.5f,0f,0f]