#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.156 ^1.586 ^0.114 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.012 ^1.597 ^0.115 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.156 ^1.586 ^0.114 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.156 ^1.586 ^0.114 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.156 ^1.586 ^0.114 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.52 ^1.555 ^0.037 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.52 ^1.555 ^0.037 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.52 ^1.555 ^0.037 ~ ~