#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [62.5f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [62.4574f,0.6518f,-7.4718f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [62.5f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [62.5f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [51.2199f,32.2248f,22.1397f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [51.2199f,32.2248f,22.1397f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [51.2199f,32.2248f,22.1397f]