#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/w_hall_corner_twitching/tree/right_upper_ear_display_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/w_hall_corner_twitching/tree/right_upper_ear_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [60f,0f,0f]