#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.162 ^1.175 ^-0.054 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.249 ^1.149 ^-0.056 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.162 ^1.175 ^-0.054 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.162 ^1.175 ^-0.054 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.162 ^1.175 ^-0.054 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.148 ^1.236 ^-0.204 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.148 ^1.236 ^-0.204 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.148 ^1.236 ^-0.204 ~ ~