#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[type=minecraft:area_effect_cloud] run function bonnie:animations/w_hall_corner_twitching/tree/root_bone_name
execute if entity @s[type=minecraft:armor_stand] run function bonnie:animations/w_hall_corner_twitching/tree/display_bone_name