#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation .this aj.id = @s aj.id
scoreboard players operation .this aj.frame = @s aj.frame
execute rotated ~ 0 as @e[type=#right_door:bone_entities,tag=aj.right_door.bone,distance=..4.537999999999999] if score @s aj.id = .this aj.id run function right_door:animations/open/tree/trunk
scoreboard players operation @s aj.frame += .aj.right_door.framerate aj.i
scoreboard players set .aj.animation aj.right_door.animating 1
execute unless score @s aj.frame matches 0..10 run function right_door:animations/open/edge