#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.bonnie.w_hall_corner.loopMode matches 0 run function bonnie:animations/w_hall_corner/stop
execute if score @s aj.bonnie.w_hall_corner.loopMode matches 1 run function bonnie:animations/w_hall_corner/pause
execute if score @s aj.bonnie.w_hall_corner.loopMode matches 2 run function bonnie:animations/w_hall_corner/zzz/execute/135