#Project generated by Animated Java (https://animated-java.dev/)

tp @s ~ ~ ~ ~ ~
execute store result score @s aj.id run scoreboard players add .aj.last_id aj.i 1
execute at @s run function chica:summon/zzz/execute/18
tag @s remove new
scoreboard players set @s aj.chica.show_stage.loopMode 2
scoreboard players set @s aj.chica.dining_area1.loopMode 2
scoreboard players set @s aj.chica.dining_area2.loopMode 2
scoreboard players set @s aj.chica.east_hall1.loopMode 2
scoreboard players set @s aj.chica.east_hall2.loopMode 2
scoreboard players set @s aj.chica.e_hall_corner.loopMode 2
scoreboard players set @s aj.chica.e_hall_corner_twitching.loopMode 2
scoreboard players set @s aj.chica.restrooms1.loopMode 2
scoreboard players set @s aj.chica.restrooms2.loopMode 2
scoreboard players set @s aj.chica.door.loopMode 2
scoreboard players set @s aj.chica.jumpscare.loopMode 2
scoreboard players set @s aj.frame 0
scoreboard players set @s aj.chica.animating 0