#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/dining_area1/tree/left_eyebrow_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^0.144 ^0.556 ^0.216 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.144 ^0.556 ^0.216 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.144 ^0.556 ^0.216 ~ ~