#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/dining_area2/tree/right_hand_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^-0.664 ^-0.239 ^-0.188 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.664 ^-0.239 ^-0.188 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.664 ^-0.239 ^-0.188 ~ ~