#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.door_right.bone.wall] run function door_right:animations/close/tree/wall_display_top
execute if entity @s[tag=aj.door_right.bone.door] run function door_right:animations/close/tree/door_display_top
execute positioned as @s run tp @s ~ ~ ~ ~ ~