#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.chica.bone.left_leg] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.chica.bone.left_lower_leg] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.chica.bone.right_leg] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.chica.bone.right_lower_leg] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.chica.bone.body] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.chica.bone.head] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.chica.bone.jaw] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.chica.bone.eyes] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.chica.bone.eyelids] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.chica.bone.pupils] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.chica.bone.right_arm] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.chica.bone.right_hand] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.chica.bone.left_arm] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.chica.bone.left_hand] Pose.Head set value [0f,0f,0f]
tp @s ~ ~ ~ ~ ~