#Project generated by Animated Java (https://animated-java.dev/)

tp @s[tag=aj.chica.bone.left_leg] ^0.269 ^-0.444 ^0
tp @s[tag=aj.chica.bone.left_lower_leg] ^0.269 ^-1.032 ^-0.062
tp @s[tag=aj.chica.bone.right_leg] ^-0.219 ^-0.444 ^-0.062
tp @s[tag=aj.chica.bone.right_lower_leg] ^-0.222 ^-1.029 ^-0.062
tp @s[tag=aj.chica.bone.body] ^0.025 ^-0.444 ^0
tp @s[tag=aj.chica.bone.head] ^0.023 ^0.426 ^0
tp @s[tag=aj.chica.bone.jaw] ^0.023 ^0.516 ^0.118
tp @s[tag=aj.chica.bone.eyes] ^0.023 ^0.831 ^0.056
tp @s[tag=aj.chica.bone.eyelids] ^0.023 ^0.876 ^0.056
tp @s[tag=aj.chica.bone.pupils] ^0.023 ^0.825 ^0.056
tp @s[tag=aj.chica.bone.right_arm] ^-0.371 ^0.206 ^0
tp @s[tag=aj.chica.bone.right_hand] ^-0.984 ^0.206 ^-0.056
tp @s[tag=aj.chica.bone.left_arm] ^0.416 ^0.206 ^-0.056
tp @s[tag=aj.chica.bone.left_hand] ^1.029 ^0.206 ^-0.056
execute store result score .calc aj.i run data get entity @s Air
execute store result entity @s Air short 1 run scoreboard players add .calc aj.i 2