#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set # aj.i 1
execute at @s as @e[type=#chica:bone_entities,tag=aj.chica.bone] if score @s aj.id = .this aj.id run function chica:zzz/execute/85