#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[type=minecraft:area_effect_cloud] run function chica:zzz/execute/89
execute if entity @s[type=minecraft:armor_stand] run tp @s ~ ~ ~ ~ ~