#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.chica.anim.show_stage] at @s run function chica:animations/show_stage/next_frame
execute if entity @s[tag=aj.chica.anim.dining_area1] at @s run function chica:animations/dining_area1/next_frame
execute if entity @s[tag=aj.chica.anim.dining_area2] at @s run function chica:animations/dining_area2/next_frame
execute if entity @s[tag=aj.chica.anim.east_hall1] at @s run function chica:animations/east_hall1/next_frame
execute if entity @s[tag=aj.chica.anim.east_hall2] at @s run function chica:animations/east_hall2/next_frame
execute if entity @s[tag=aj.chica.anim.e_hall_corner] at @s run function chica:animations/e_hall_corner/next_frame
execute if entity @s[tag=aj.chica.anim.e_hall_corner_twitching] at @s run function chica:animations/e_hall_corner_twitching/next_frame
execute if entity @s[tag=aj.chica.anim.restrooms1] at @s run function chica:animations/restrooms1/next_frame
execute if entity @s[tag=aj.chica.anim.restrooms2] at @s run function chica:animations/restrooms2/next_frame
execute if entity @s[tag=aj.chica.anim.door] at @s run function chica:animations/door/next_frame
execute if entity @s[tag=aj.chica.anim.jumpscare] at @s run function chica:animations/jumpscare/next_frame
scoreboard players operation @s aj.chica.animating = .aj.animation aj.chica.animating