#Project generated by Animated Java (https://animated-java.dev/)

schedule function left_door:animation_loop 1t
scoreboard players set .aj.anim_loop aj.left_door.animating 1
scoreboard players set .aj.animation aj.left_door.animating 0
execute as @e[type=minecraft:marker,tag=aj.left_door.root] run function left_door:zzz/execute/20
execute if score .aj.animation aj.left_door.animating matches 0 run function left_door:zzz/execute/21