#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.bonnie.bone.head] run function bonnie:animations/backstage_creepy/tree/head_display_top
execute if entity @s[tag=aj.bonnie.bone.eyes] run function bonnie:animations/backstage_creepy/tree/eyes_display_top
execute if entity @s[tag=aj.bonnie.bone.left_ear] run function bonnie:animations/backstage_creepy/tree/left_ear_display_top
execute if entity @s[tag=aj.bonnie.bone.right_ear] run function bonnie:animations/backstage_creepy/tree/right_ear_display_top
execute if entity @s[tag=aj.bonnie.bone.left_upper_ear] run function bonnie:animations/backstage_creepy/tree/left_upper_ear_display_top
execute if entity @s[tag=aj.bonnie.bone.right_upper_ear] run function bonnie:animations/backstage_creepy/tree/right_upper_ear_display_top
execute if entity @s[tag=aj.bonnie.bone.jaw] run function bonnie:animations/backstage_creepy/tree/jaw_display_top
execute if entity @s[tag=aj.bonnie.bone.body] run function bonnie:animations/backstage_creepy/tree/body_display_top
execute if entity @s[tag=aj.bonnie.bone.left_arm] run function bonnie:animations/backstage_creepy/tree/left_arm_display_top
execute if entity @s[tag=aj.bonnie.bone.left_hand] run function bonnie:animations/backstage_creepy/tree/left_hand_display_top
execute if entity @s[tag=aj.bonnie.bone.right_hand] run function bonnie:animations/backstage_creepy/tree/right_hand_display_top
execute if entity @s[tag=aj.bonnie.bone.right_arm] run function bonnie:animations/backstage_creepy/tree/right_arm_display_top
execute if entity @s[tag=aj.bonnie.bone.left_leg] run function bonnie:animations/backstage_creepy/tree/left_leg_display_top
execute if entity @s[tag=aj.bonnie.bone.left_lower_leg] run function bonnie:animations/backstage_creepy/tree/left_lower_leg_display_top
execute if entity @s[tag=aj.bonnie.bone.right_leg] run function bonnie:animations/backstage_creepy/tree/right_leg_display_top
execute if entity @s[tag=aj.bonnie.bone.right_lower_leg] run function bonnie:animations/backstage_creepy/tree/right_lower_leg_display_top
execute if entity @s[tag=aj.bonnie.bone.pupils] run function bonnie:animations/backstage_creepy/tree/pupils_display_top
execute if entity @s[tag=aj.bonnie.bone.eyelids] run function bonnie:animations/backstage_creepy/tree/eyelids_display_top
execute if entity @s[tag=aj.bonnie.bone.guitar] run function bonnie:animations/backstage_creepy/tree/guitar_display_top
execute positioned as @s run tp @s ~ ~ ~ ~ ~