#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [-7.0458f,-12.6812f,-1.8848f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-7.0458f,-12.6812f,-1.8848f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-7.0458f,-12.6812f,-1.8848f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-7.0458f,-12.6812f,-1.8848f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-7.0458f,-12.6812f,-1.8848f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-7.0458f,-12.6812f,-1.8848f]