#Project generated by Animated Java (https://animated-java.dev/)

tp @s ~ ~ ~ ~ ~
execute store result score @s aj.id run scoreboard players add .aj.last_id aj.i 1
execute at @s run function freddy:summon/zzz/execute/36
tag @s remove new
scoreboard players set @s aj.freddy.show_stage.loopMode 2
scoreboard players set @s aj.freddy.show_stage_alone.loopMode 2
scoreboard players set @s aj.freddy.dining_area.loopMode 2
scoreboard players set @s aj.freddy.restrooms.loopMode 2
scoreboard players set @s aj.freddy.east_hall.loopMode 2
scoreboard players set @s aj.freddy.e_hall_corner.loopMode 2
scoreboard players set @s aj.freddy.jumpscare_powerout.loopMode 1
scoreboard players set @s aj.freddy.jumpscare_office.loopMode 1
scoreboard players set @s aj.freddy.powerout.loopMode 2
scoreboard players set @s aj.frame 0
scoreboard players set @s aj.freddy.animating 0