#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.right_door.close.loopMode matches 0 run function right_door:animations/close/stop
execute if score @s aj.right_door.close.loopMode matches 1 run function right_door:animations/close/pause
execute if score @s aj.right_door.close.loopMode matches 2 run function right_door:animations/close/zzz/execute/19