#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.freddy.bone.head] run function freddy:animations/restrooms/tree/head_display_top
execute if entity @s[tag=aj.freddy.bone.jaw] run function freddy:animations/restrooms/tree/jaw_display_top
execute if entity @s[tag=aj.freddy.bone.body] run function freddy:animations/restrooms/tree/body_display_top
execute if entity @s[tag=aj.freddy.bone.left_hand] run function freddy:animations/restrooms/tree/left_hand_display_top
execute if entity @s[tag=aj.freddy.bone.right_hand] run function freddy:animations/restrooms/tree/right_hand_display_top
execute if entity @s[tag=aj.freddy.bone.right_arm] run function freddy:animations/restrooms/tree/right_arm_display_top
execute if entity @s[tag=aj.freddy.bone.left_lower_leg] run function freddy:animations/restrooms/tree/left_lower_leg_display_top
execute if entity @s[tag=aj.freddy.bone.right_leg] run function freddy:animations/restrooms/tree/right_leg_display_top
execute if entity @s[tag=aj.freddy.bone.eyes] run function freddy:animations/restrooms/tree/eyes_display_top
execute if entity @s[tag=aj.freddy.bone.left_arm] run function freddy:animations/restrooms/tree/left_arm_display_top
execute if entity @s[tag=aj.freddy.bone.left_leg] run function freddy:animations/restrooms/tree/left_leg_display_top
execute if entity @s[tag=aj.freddy.bone.right_lower_leg] run function freddy:animations/restrooms/tree/right_lower_leg_display_top
execute if entity @s[tag=aj.freddy.bone.pupils] run function freddy:animations/restrooms/tree/pupils_display_top
execute if entity @s[tag=aj.freddy.bone.eyelids] run function freddy:animations/restrooms/tree/eyelids_display_top
execute positioned as @s run tp @s ~ ~ ~ ~ ~