#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,2.5f,-25f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [0f,2.5f,-25f]