#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.freddy.bone.head] run function freddy:animations/restrooms/tree/head_root_top
execute if entity @s[tag=aj.freddy.bone.jaw] run function freddy:animations/restrooms/tree/jaw_root_top
execute if entity @s[tag=aj.freddy.bone.body] run function freddy:animations/restrooms/tree/body_root_top
execute if entity @s[tag=aj.freddy.bone.left_hand] run function freddy:animations/restrooms/tree/left_hand_root_top
execute if entity @s[tag=aj.freddy.bone.right_hand] run function freddy:animations/restrooms/tree/right_hand_root_top
execute if entity @s[tag=aj.freddy.bone.right_arm] run function freddy:animations/restrooms/tree/right_arm_root_top
execute if entity @s[tag=aj.freddy.bone.left_lower_leg] run function freddy:animations/restrooms/tree/left_lower_leg_root_top
execute if entity @s[tag=aj.freddy.bone.right_leg] run function freddy:animations/restrooms/tree/right_leg_root_top
execute if entity @s[tag=aj.freddy.bone.eyes] run function freddy:animations/restrooms/tree/eyes_root_top
execute if entity @s[tag=aj.freddy.bone.left_arm] run function freddy:animations/restrooms/tree/left_arm_root_top
execute if entity @s[tag=aj.freddy.bone.left_leg] run function freddy:animations/restrooms/tree/left_leg_root_top
execute if entity @s[tag=aj.freddy.bone.right_lower_leg] run function freddy:animations/restrooms/tree/right_lower_leg_root_top
execute if entity @s[tag=aj.freddy.bone.pupils] run function freddy:animations/restrooms/tree/pupils_root_top
execute if entity @s[tag=aj.freddy.bone.eyelids] run function freddy:animations/restrooms/tree/eyelids_root_top
execute store result entity @s Air short 1 run scoreboard players get .this aj.frame