#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,12.5f,-40f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [0f,12.5f,-40f]