#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.freddy.bone.left_leg] ArmorItems[-1].tag.CustomModelData set value 815
data modify entity @s[tag=aj.freddy.bone.left_lower_leg] ArmorItems[-1].tag.CustomModelData set value 816
data modify entity @s[tag=aj.freddy.bone.right_leg] ArmorItems[-1].tag.CustomModelData set value 817
data modify entity @s[tag=aj.freddy.bone.right_lower_leg] ArmorItems[-1].tag.CustomModelData set value 818
data modify entity @s[tag=aj.freddy.bone.body] ArmorItems[-1].tag.CustomModelData set value 819
data modify entity @s[tag=aj.freddy.bone.left_arm] ArmorItems[-1].tag.CustomModelData set value 820
data modify entity @s[tag=aj.freddy.bone.left_hand] ArmorItems[-1].tag.CustomModelData set value 821
data modify entity @s[tag=aj.freddy.bone.right_arm] ArmorItems[-1].tag.CustomModelData set value 822
data modify entity @s[tag=aj.freddy.bone.right_hand] ArmorItems[-1].tag.CustomModelData set value 823
data modify entity @s[tag=aj.freddy.bone.head] ArmorItems[-1].tag.CustomModelData set value 824
data modify entity @s[tag=aj.freddy.bone.eyes] ArmorItems[-1].tag.CustomModelData set value 825
data modify entity @s[tag=aj.freddy.bone.eyelids] ArmorItems[-1].tag.CustomModelData set value 826
data modify entity @s[tag=aj.freddy.bone.pupils] ArmorItems[-1].tag.CustomModelData set value 827
data modify entity @s[tag=aj.freddy.bone.jaw] ArmorItems[-1].tag.CustomModelData set value 828