#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.freddy.bone.left_leg] ArmorItems[-1].tag.CustomModelData set value 857
data modify entity @s[tag=aj.freddy.bone.left_lower_leg] ArmorItems[-1].tag.CustomModelData set value 858
data modify entity @s[tag=aj.freddy.bone.right_leg] ArmorItems[-1].tag.CustomModelData set value 859
data modify entity @s[tag=aj.freddy.bone.right_lower_leg] ArmorItems[-1].tag.CustomModelData set value 860
data modify entity @s[tag=aj.freddy.bone.body] ArmorItems[-1].tag.CustomModelData set value 861
data modify entity @s[tag=aj.freddy.bone.left_arm] ArmorItems[-1].tag.CustomModelData set value 862
data modify entity @s[tag=aj.freddy.bone.left_hand] ArmorItems[-1].tag.CustomModelData set value 863
data modify entity @s[tag=aj.freddy.bone.right_arm] ArmorItems[-1].tag.CustomModelData set value 864
data modify entity @s[tag=aj.freddy.bone.right_hand] ArmorItems[-1].tag.CustomModelData set value 865
data modify entity @s[tag=aj.freddy.bone.head] ArmorItems[-1].tag.CustomModelData set value 866
data modify entity @s[tag=aj.freddy.bone.eyes] ArmorItems[-1].tag.CustomModelData set value 867
data modify entity @s[tag=aj.freddy.bone.eyelids] ArmorItems[-1].tag.CustomModelData set value 868
data modify entity @s[tag=aj.freddy.bone.pupils] ArmorItems[-1].tag.CustomModelData set value 869
data modify entity @s[tag=aj.freddy.bone.jaw] ArmorItems[-1].tag.CustomModelData set value 870