#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.freddy.bone.left_leg] ArmorItems[-1].tag.CustomModelData set value 871
data modify entity @s[tag=aj.freddy.bone.left_lower_leg] ArmorItems[-1].tag.CustomModelData set value 872
data modify entity @s[tag=aj.freddy.bone.right_leg] ArmorItems[-1].tag.CustomModelData set value 873
data modify entity @s[tag=aj.freddy.bone.right_lower_leg] ArmorItems[-1].tag.CustomModelData set value 874
data modify entity @s[tag=aj.freddy.bone.body] ArmorItems[-1].tag.CustomModelData set value 875
data modify entity @s[tag=aj.freddy.bone.left_arm] ArmorItems[-1].tag.CustomModelData set value 876
data modify entity @s[tag=aj.freddy.bone.left_hand] ArmorItems[-1].tag.CustomModelData set value 877
data modify entity @s[tag=aj.freddy.bone.right_arm] ArmorItems[-1].tag.CustomModelData set value 878
data modify entity @s[tag=aj.freddy.bone.right_hand] ArmorItems[-1].tag.CustomModelData set value 879
data modify entity @s[tag=aj.freddy.bone.head] ArmorItems[-1].tag.CustomModelData set value 880
data modify entity @s[tag=aj.freddy.bone.eyes] ArmorItems[-1].tag.CustomModelData set value 881
data modify entity @s[tag=aj.freddy.bone.eyelids] ArmorItems[-1].tag.CustomModelData set value 882
data modify entity @s[tag=aj.freddy.bone.pupils] ArmorItems[-1].tag.CustomModelData set value 883
data modify entity @s[tag=aj.freddy.bone.jaw] ArmorItems[-1].tag.CustomModelData set value 884