#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.freddy.bone.left_leg] ArmorItems[-1].tag.CustomModelData set value 885
data modify entity @s[tag=aj.freddy.bone.left_lower_leg] ArmorItems[-1].tag.CustomModelData set value 886
data modify entity @s[tag=aj.freddy.bone.right_leg] ArmorItems[-1].tag.CustomModelData set value 887
data modify entity @s[tag=aj.freddy.bone.right_lower_leg] ArmorItems[-1].tag.CustomModelData set value 888
data modify entity @s[tag=aj.freddy.bone.body] ArmorItems[-1].tag.CustomModelData set value 889
data modify entity @s[tag=aj.freddy.bone.left_arm] ArmorItems[-1].tag.CustomModelData set value 890
data modify entity @s[tag=aj.freddy.bone.left_hand] ArmorItems[-1].tag.CustomModelData set value 891
data modify entity @s[tag=aj.freddy.bone.right_arm] ArmorItems[-1].tag.CustomModelData set value 892
data modify entity @s[tag=aj.freddy.bone.right_hand] ArmorItems[-1].tag.CustomModelData set value 893
data modify entity @s[tag=aj.freddy.bone.head] ArmorItems[-1].tag.CustomModelData set value 894
data modify entity @s[tag=aj.freddy.bone.eyes] ArmorItems[-1].tag.CustomModelData set value 895
data modify entity @s[tag=aj.freddy.bone.eyelids] ArmorItems[-1].tag.CustomModelData set value 896
data modify entity @s[tag=aj.freddy.bone.pupils] ArmorItems[-1].tag.CustomModelData set value 897
data modify entity @s[tag=aj.freddy.bone.jaw] ArmorItems[-1].tag.CustomModelData set value 898