#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.freddy.bone.left_leg] ArmorItems[-1].tag.CustomModelData set value 1129
data modify entity @s[tag=aj.freddy.bone.left_lower_leg] ArmorItems[-1].tag.CustomModelData set value 1130
data modify entity @s[tag=aj.freddy.bone.right_leg] ArmorItems[-1].tag.CustomModelData set value 1131
data modify entity @s[tag=aj.freddy.bone.right_lower_leg] ArmorItems[-1].tag.CustomModelData set value 1132
data modify entity @s[tag=aj.freddy.bone.body] ArmorItems[-1].tag.CustomModelData set value 1133
data modify entity @s[tag=aj.freddy.bone.left_arm] ArmorItems[-1].tag.CustomModelData set value 1134
data modify entity @s[tag=aj.freddy.bone.left_hand] ArmorItems[-1].tag.CustomModelData set value 1135
data modify entity @s[tag=aj.freddy.bone.right_arm] ArmorItems[-1].tag.CustomModelData set value 1136
data modify entity @s[tag=aj.freddy.bone.right_hand] ArmorItems[-1].tag.CustomModelData set value 1137
data modify entity @s[tag=aj.freddy.bone.head] ArmorItems[-1].tag.CustomModelData set value 1138
data modify entity @s[tag=aj.freddy.bone.eyes] ArmorItems[-1].tag.CustomModelData set value 1139
data modify entity @s[tag=aj.freddy.bone.eyelids] ArmorItems[-1].tag.CustomModelData set value 1140
data modify entity @s[tag=aj.freddy.bone.pupils] ArmorItems[-1].tag.CustomModelData set value 1141
data modify entity @s[tag=aj.freddy.bone.jaw] ArmorItems[-1].tag.CustomModelData set value 1142