#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/e_hall_corner/tree/body_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^0.025 ^-0.444 ^0 ~ ~