#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/e_hall_corner/tree/eyelids_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^0.065 ^0.871 ^0.003 ~ ~