#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/e_hall_corner/tree/eyes_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^0.063 ^0.833 ^0.007 ~ ~