#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/e_hall_corner/tree/left_arm_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^0.416 ^0.269 ^-0.056 ~ ~