#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/e_hall_corner/tree/right_hand_display_0-7
execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [73.8048f,-10.4045f,-91.5875f]