#Project generated by Animated Java (https://animated-java.dev/)

tp @s[tag=aj.backstage.bone.static] ^0 ^-1.813 ^0
tp @s[tag=aj.backstage.bone.bonnie_static] ^0.188 ^-2.094 ^-3.062
tp @s[tag=aj.backstage.bone.jaw2] ^0.213 ^-0.558 ^-3.87
tp @s[tag=aj.backstage.bone.bonnie_static2] ^0.875 ^-0.382 ^-3.062
tp @s[tag=aj.backstage.bone.jaw3] ^-0.661 ^-0.357 ^-3.87
tp @s[tag=aj.backstage.bone.chica_static] ^-2.1 ^-1.882 ^0.438
tp @s[tag=aj.backstage.bone.head_bonnie] ^-2.125 ^-0.469 ^1.25
tp @s[tag=aj.backstage.bone.jaw4] ^-2.282 ^-0.608 ^1.613
tp @s[tag=aj.backstage.bone.head_bonnie_table] ^0.063 ^-0.444 ^-0.062
tp @s[tag=aj.backstage.bone.jaw] ^-0.304 ^0.243 ^-0.137
tp @s[tag=aj.backstage.bone.head_chica] ^0.525 ^-0.819 ^-3
tp @s[tag=aj.backstage.bone.jaw6] ^0.527 ^0.394 ^-2.858
tp @s[tag=aj.backstage.bone.head_freddy] ^-0.937 ^-0.994 ^-3.094
tp @s[tag=aj.backstage.bone.eyes] ^-0.937 ^1.11 ^-3.169
tp @s[tag=aj.backstage.bone.eyelids] ^-0.937 ^1.11 ^-3.169
tp @s[tag=aj.backstage.bone.pupils] ^-0.937 ^1.11 ^-3.169
tp @s[tag=aj.backstage.bone.jaw7] ^-0.937 ^0.734 ^-3.206
tp @s[tag=aj.backstage.bone.head_freddy2] ^1.375 ^-0.519 ^-3.187
tp @s[tag=aj.backstage.bone.eyes2] ^1.729 ^-0.519 ^-3.262
tp @s[tag=aj.backstage.bone.eyelids2] ^1.729 ^-0.519 ^-3.262
tp @s[tag=aj.backstage.bone.pupils2] ^1.729 ^-0.519 ^-3.262
tp @s[tag=aj.backstage.bone.jaw8] ^1.354 ^-0.519 ^-3.3
tp @s[tag=aj.backstage.bone.head_freddy3] ^-2.125 ^-1.019 ^1.75
tp @s[tag=aj.backstage.bone.jaw9] ^-2.237 ^0.71 ^1.75
tp @s[tag=aj.backstage.bone.body] ^-0.5 ^-0.657 ^1.813
tp @s[tag=aj.backstage.bone.head] ^-0.5 ^0.606 ^1.875
tp @s[tag=aj.backstage.bone.jaw10] ^-0.5 ^0.661 ^1.875
tp @s[tag=aj.backstage.bone.left_arm] ^-0.08 ^0.271 ^1.813
tp @s[tag=aj.backstage.bone.left_hand] ^0.573 ^0.271 ^1.813
tp @s[tag=aj.backstage.bone.right_arm] ^-0.92 ^0.271 ^1.813
tp @s[tag=aj.backstage.bone.right_hand] ^-1.572 ^0.271 ^1.813
tp @s[tag=aj.backstage.bone.right_leg] ^-0.687 ^-0.753 ^1.813
tp @s[tag=aj.backstage.bone.right_lower_leg] ^-0.687 ^-1.409 ^1.8
tp @s[tag=aj.backstage.bone.left_leg] ^-0.32 ^-0.747 ^1.8
tp @s[tag=aj.backstage.bone.left_lower_leg] ^-0.317 ^-1.4 ^1.805
execute store result score .calc aj.i run data get entity @s Air
execute store result entity @s Air short 1 run scoreboard players add .calc aj.i 2