#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.backstage.anim.normal] at @s run function backstage:animations/normal/next_frame
execute if entity @s[tag=aj.backstage.anim.easter_egg] at @s run function backstage:animations/easter_egg/next_frame
execute if entity @s[tag=aj.backstage.anim.game_over] at @s run function backstage:animations/game_over/next_frame
scoreboard players operation @s aj.backstage.animating = .aj.animation aj.backstage.animating