#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [1.1188f,-14.9512f,-92.6707f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [1.1188f,-14.9512f,-92.6707f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [1.1188f,-14.9512f,-92.6707f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [1.1188f,-14.9512f,-92.6707f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [1.1188f,-14.9512f,-92.6707f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [1.1188f,-14.9512f,-92.6707f]