#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.chica.anim.e_hall_corner_twitching
execute if score .aj.chica.framerate aj.i matches ..-1 run scoreboard players set @s aj.frame 19
execute if score .aj.chica.framerate aj.i matches 1.. run scoreboard players set @s aj.frame 0
scoreboard players add .noScripts aj.i 0
execute if score .aj.anim_loop aj.chica.animating matches 0 run function chica:animation_loop
scoreboard players set #execute aj.i 1