#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.chica.east_hall2.loopMode matches 0 run function chica:animations/east_hall2/stop
execute if score @s aj.chica.east_hall2.loopMode matches 1 run function chica:animations/east_hall2/pause
execute if score @s aj.chica.east_hall2.loopMode matches 2 run function chica:animations/east_hall2/zzz/execute/100