#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/jumpscare/tree/body_display_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/jumpscare/tree/body_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [25f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [23.125f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [21.25f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [19.375f,0f,0f]