#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/jumpscare/tree/eyelids_root_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/jumpscare/tree/eyelids_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0.03 ^0.677 ^0.652 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.04 ^0.736 ^0.546 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.047 ^0.776 ^0.43 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.09 ^0.789 ^0.319 ~ ~