#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.041 ^0.787 ^0.711 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.054 ^0.856 ^0.577 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.063 ^0.9 ^0.433 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.12 ^0.908 ^0.295 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.174 ^0.886 ^0.158 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.12 ^0.908 ^0.295 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.063 ^0.9 ^0.433 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.054 ^0.856 ^0.577 ~ ~