#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/jumpscare/tree/eyes_root_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/jumpscare/tree/eyes_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0.032 ^0.686 ^0.742 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.045 ^0.765 ^0.631 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.055 ^0.824 ^0.506 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.106 ^0.85 ^0.383 ~ ~