#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.032 ^0.686 ^0.742 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.045 ^0.765 ^0.631 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.055 ^0.824 ^0.506 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.106 ^0.85 ^0.383 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.157 ^0.85 ^0.256 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.106 ^0.85 ^0.383 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.055 ^0.824 ^0.506 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.045 ^0.765 ^0.631 ~ ~