#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-1.756 ^-0.136 ^0.929 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-1.756 ^-0.104 ^0.91 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-1.756 ^-0.072 ^0.89 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-1.756 ^-0.041 ^0.869 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-1.756 ^-0.011 ^0.847 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-1.756 ^-0.041 ^0.869 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-1.756 ^-0.072 ^0.89 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-1.756 ^-0.104 ^0.91 ~ ~