#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-1.756 ^-0.136 ^0.929 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-1.756 ^-0.104 ^0.91 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-1.756 ^-0.072 ^0.89 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-1.756 ^-0.041 ^0.869 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-1.756 ^-0.011 ^0.847 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-1.756 ^-0.041 ^0.869 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-1.756 ^-0.072 ^0.89 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-1.756 ^-0.104 ^0.91 ~ ~