#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/jumpscare/tree/guitar_display_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/jumpscare/tree/guitar_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [0f,25f,-90f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [0f,23.125f,-90f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [0f,21.25f,-90f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [0f,19.375f,-90f]