#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/jumpscare/tree/guitar_root_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/jumpscare/tree/guitar_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^-1.756 ^-0.136 ^0.929 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-1.756 ^-0.104 ^0.91 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-1.756 ^-0.072 ^0.89 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-1.756 ^-0.041 ^0.869 ~ ~