#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-1.756 ^-0.136 ^0.929 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-1.756 ^-0.104 ^0.91 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-1.756 ^-0.072 ^0.89 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-1.756 ^-0.041 ^0.869 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-1.756 ^-0.011 ^0.847 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-1.756 ^-0.041 ^0.869 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-1.756 ^-0.072 ^0.89 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-1.756 ^-0.104 ^0.91 ~ ~