#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,25f,-90f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [0f,21.25f,-90f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [0f,17.5f,-90f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [0f,21.25f,-90f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [0f,25f,-90f]