#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/jumpscare/tree/head_root_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/jumpscare/tree/head_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0 ^0.401 ^0.428 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0 ^0.417 ^0.392 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0 ^0.431 ^0.355 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0 ^0.444 ^0.318 ~ ~