#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^0.401 ^0.428 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^0.417 ^0.392 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^0.431 ^0.355 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^0.444 ^0.318 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^0.456 ^0.28 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^0.444 ^0.318 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^0.431 ^0.355 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^0.417 ^0.392 ~ ~