#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.001 ^-0.002 ^0.305 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.003 ^-0.004 ^0.238 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.009 ^-0.007 ^0.181 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.003 ^-0.004 ^0.238 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.001 ^-0.002 ^0.305 ~ ~