#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/jumpscare/tree/jaw_root_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/jumpscare/tree/jaw_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0.008 ^0.511 ^0.394 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.008 ^0.515 ^0.333 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.006 ^0.514 ^0.275 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.014 ^0.507 ^0.223 ~ ~