#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.008 ^0.511 ^0.394 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.008 ^0.515 ^0.333 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.006 ^0.514 ^0.275 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.014 ^0.507 ^0.223 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.016 ^0.496 ^0.174 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.014 ^0.507 ^0.223 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.006 ^0.514 ^0.275 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.008 ^0.515 ^0.333 ~ ~