#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [34.4076f,-1.558f,4.7883f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [20.0842f,-2.7115f,6.9953f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [31.9465f,0.1996f,21.7525f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [20.0842f,-2.7115f,6.9953f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [34.4076f,-1.558f,4.7883f]