#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.162 ^0.328 ^0.589 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.179 ^0.412 ^0.334 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.27 ^0.354 ^0.096 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.179 ^0.412 ^0.334 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.162 ^0.328 ^0.589 ~ ~