#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/jumpscare/tree/left_hand_display_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/jumpscare/tree/left_hand_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-7.5208f,-40.4609f,88.2607f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-9.1009f,-40.7303f,88.7132f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-10.7166f,-40.9889f,89.2342f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-12.3665f,-41.2347f,89.8235f]