#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/jumpscare/tree/left_upper_ear_display_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/jumpscare/tree/left_upper_ear_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [80.4076f,-1.558f,4.7883f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [66.9968f,-2.17f,5.8694f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [53.5842f,-2.7115f,6.9953f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [41.5815f,-1.5289f,14.431f]