#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.214 ^0.973 ^0.77 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.23 ^1.048 ^0.586 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.24 ^1.087 ^0.392 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.317 ^1.059 ^0.215 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.383 ^0.991 ^0.043 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.317 ^1.059 ^0.215 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.24 ^1.087 ^0.392 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.23 ^1.048 ^0.586 ~ ~