#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/jumpscare/tree/left_upper_ear_root_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/jumpscare/tree/left_upper_ear_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0.249 ^1.291 ^1.067 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.277 ^1.426 ^0.802 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.297 ^1.504 ^0.513 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.426 ^1.482 ^0.247 ~ ~