#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [17.527f,-37.7185f,49.4572f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [15.5512f,-39.6591f,49.5806f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [13.4278f,-41.6372f,50.0138f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [15.5512f,-39.6591f,49.5806f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [17.527f,-37.7185f,49.4572f]