#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.645 ^-0.103 ^0.027 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.642 ^-0.085 ^-0.012 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.637 ^-0.069 ^-0.05 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.632 ^-0.053 ^-0.089 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.626 ^-0.039 ^-0.128 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.632 ^-0.053 ^-0.089 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.637 ^-0.069 ^-0.05 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.642 ^-0.085 ^-0.012 ~ ~