#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.645 ^-0.103 ^0.027 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.642 ^-0.085 ^-0.012 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.637 ^-0.069 ^-0.05 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.632 ^-0.053 ^-0.089 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.626 ^-0.039 ^-0.128 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.632 ^-0.053 ^-0.089 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.637 ^-0.069 ^-0.05 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.642 ^-0.085 ^-0.012 ~ ~