#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.249 ^1.291 ^1.067 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.277 ^1.426 ^0.802 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.297 ^1.504 ^0.513 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.426 ^1.482 ^0.247 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.543 ^1.393 ^-0.018 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.426 ^1.482 ^0.247 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.297 ^1.504 ^0.513 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.277 ^1.426 ^0.802 ~ ~