#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.249 ^1.291 ^1.067 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.277 ^1.426 ^0.802 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.297 ^1.504 ^0.513 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.426 ^1.482 ^0.247 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.543 ^1.393 ^-0.018 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.426 ^1.482 ^0.247 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.297 ^1.504 ^0.513 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.277 ^1.426 ^0.802 ~ ~