#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.506 ^-0.465 ^0.013 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.5 ^-0.437 ^-0.047 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.491 ^-0.414 ^-0.109 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.5 ^-0.437 ^-0.047 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.506 ^-0.465 ^0.013 ~ ~