#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/jumpscare/tree/left_ear_root_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/jumpscare/tree/left_ear_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0.214 ^0.973 ^0.77 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.23 ^1.048 ^0.586 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.24 ^1.087 ^0.392 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.317 ^1.059 ^0.215 ~ ~