#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.214 ^0.973 ^0.77 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.23 ^1.048 ^0.586 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.24 ^1.087 ^0.392 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.317 ^1.059 ^0.215 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.383 ^0.991 ^0.043 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.317 ^1.059 ^0.215 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.24 ^1.087 ^0.392 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.23 ^1.048 ^0.586 ~ ~