#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [27.9076f,-1.558f,4.7883f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [14.4968f,-2.17f,5.8694f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [1.0842f,-2.7115f,6.9953f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-10.9185f,-1.5289f,14.431f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-23.0535f,0.1996f,21.7525f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-10.9185f,-1.5289f,14.431f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [1.0842f,-2.7115f,6.9953f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [14.4968f,-2.17f,5.8694f]