#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/jumpscare/tree/pupils_root_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/jumpscare/tree/pupils_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0.028 ^0.683 ^0.774 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.041 ^0.761 ^0.661 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.051 ^0.818 ^0.536 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.102 ^0.851 ^0.414 ~ ~