#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/jumpscare/tree/right_hand_display_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/jumpscare/tree/right_hand_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [1.1099f,41.0231f,-75.0704f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-0.441f,40.8369f,-75.4652f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-2.0172f,40.6447f,-75.9085f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-3.6167f,40.4449f,-76.3996f]