#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.567 ^-0.424 ^0.035 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.562 ^-0.401 ^-0.021 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.556 ^-0.383 ^-0.078 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.562 ^-0.401 ^-0.021 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.567 ^-0.424 ^0.035 ~ ~