#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.069 ^1.317 ^1.077 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.04 ^1.458 ^0.815 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.019 ^1.542 ^0.529 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.118 ^1.561 ^0.257 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.248 ^1.512 ^-0.018 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.118 ^1.561 ^0.257 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.019 ^1.542 ^0.529 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.04 ^1.458 ^0.815 ~ ~