#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [24.3162f,34.1333f,-37.9174f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [21.7516f,35.2717f,-38.1708f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [19.0577f,36.4583f,-38.6893f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [21.7516f,35.2717f,-38.1708f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [24.3162f,34.1333f,-37.9174f]