#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [24.3162f,34.1333f,-37.9174f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [23.0496f,34.6953f,-38.012f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [21.7516f,35.2717f,-38.1708f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [20.4213f,35.8601f,-38.3959f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [19.0577f,36.4583f,-38.6893f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [20.4213f,35.8601f,-38.3959f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [21.7516f,35.2717f,-38.1708f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [23.0496f,34.6953f,-38.012f]