#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.73 ^-0.051 ^0.055 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.727 ^-0.036 ^0.02 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.724 ^-0.023 ^-0.016 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.72 ^-0.01 ^-0.052 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.716 ^0.001 ^-0.089 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.72 ^-0.01 ^-0.052 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.724 ^-0.023 ^-0.016 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.727 ^-0.036 ^0.02 ~ ~