#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/jumpscare/tree/right_upper_ear_root_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/jumpscare/tree/right_upper_ear_root_8-15
execute if score .this aj.frame matches 16..23 run function bonnie:animations/jumpscare/tree/right_upper_ear_root_16-23