#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [42.9076f,-1.558f,4.7883f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [29.4968f,-2.17f,5.8694f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [16.0842f,-2.7115f,6.9953f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [4.0815f,-1.5289f,14.431f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-8.0535f,0.1996f,21.7525f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [4.0815f,-1.5289f,14.431f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [16.0842f,-2.7115f,6.9953f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [29.4968f,-2.17f,5.8694f]