#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.104 ^0.994 ^0.775 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.088 ^1.075 ^0.597 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.077 ^1.12 ^0.407 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.007 ^1.133 ^0.225 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.085 ^1.104 ^0.044 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.007 ^1.133 ^0.225 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.077 ^1.12 ^0.407 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.088 ^1.075 ^0.597 ~ ~