#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.362 ^0.235 ^0.371 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.362 ^0.248 ^0.34 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.362 ^0.261 ^0.309 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.362 ^0.273 ^0.278 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.362 ^0.283 ^0.246 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.362 ^0.273 ^0.278 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.362 ^0.261 ^0.309 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.362 ^0.248 ^0.34 ~ ~