#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.069 ^1.317 ^1.077 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.04 ^1.458 ^0.815 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.019 ^1.542 ^0.529 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.118 ^1.561 ^0.257 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.248 ^1.512 ^-0.018 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.118 ^1.561 ^0.257 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.019 ^1.542 ^0.529 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.04 ^1.458 ^0.815 ~ ~