#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.069 ^1.317 ^1.077 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.04 ^1.458 ^0.815 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.019 ^1.542 ^0.529 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.118 ^1.561 ^0.257 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.248 ^1.512 ^-0.018 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.118 ^1.561 ^0.257 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.019 ^1.542 ^0.529 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.04 ^1.458 ^0.815 ~ ~