#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [42.9076f,-1.558f,4.7883f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [29.4968f,-2.17f,5.8694f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [16.0842f,-2.7115f,6.9953f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [4.0815f,-1.5289f,14.431f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-8.0535f,0.1996f,21.7525f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [4.0815f,-1.5289f,14.431f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [16.0842f,-2.7115f,6.9953f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [29.4968f,-2.17f,5.8694f]