#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.73 ^-0.051 ^0.055 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.727 ^-0.036 ^0.02 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.724 ^-0.023 ^-0.016 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.72 ^-0.01 ^-0.052 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.716 ^0.001 ^-0.089 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.72 ^-0.01 ^-0.052 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.724 ^-0.023 ^-0.016 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.727 ^-0.036 ^0.02 ~ ~