#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/jumpscare/tree/right_upper_ear_root_0-7
execute if score .this aj.frame matches 8..15 run function bonnie:animations/jumpscare/tree/right_upper_ear_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^-0.069 ^1.317 ^1.077 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.04 ^1.458 ^0.815 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.019 ^1.542 ^0.529 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.118 ^1.561 ^0.257 ~ ~