#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.057 ^0.622 ^0.851 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.02 ^0.8 ^0.449 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.176 ^0.792 ^0.043 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.02 ^0.8 ^0.449 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.057 ^0.622 ^0.851 ~ ~