#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.104 ^0.994 ^0.775 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.088 ^1.075 ^0.597 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.077 ^1.12 ^0.407 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.007 ^1.133 ^0.225 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.085 ^1.104 ^0.044 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.007 ^1.133 ^0.225 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.077 ^1.12 ^0.407 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.088 ^1.075 ^0.597 ~ ~