#Project generated by Animated Java (https://animated-java.dev/)

tp @s[tag=aj.gfreddy.bone.left_leg] ^0.156 ^-2.313 ^0.25
tp @s[tag=aj.gfreddy.bone.left_lower_leg] ^0.156 ^-1.768 ^0.58
tp @s[tag=aj.gfreddy.bone.left_foot] ^0.195 ^-2.125 ^0.686
tp @s[tag=aj.gfreddy.bone.right_leg] ^-0.156 ^-2.313 ^0.25
tp @s[tag=aj.gfreddy.bone.right_lower_leg] ^-0.156 ^-1.768 ^0.58
tp @s[tag=aj.gfreddy.bone.right_foot] ^-0.189 ^-2.12 ^0.704
tp @s[tag=aj.gfreddy.bone.body] ^0 ^-2.375 ^-0.062
tp @s[tag=aj.gfreddy.bone.left_arm] ^0.338 ^-1.388 ^-0.075
tp @s[tag=aj.gfreddy.bone.left_lower_arm] ^0.451 ^-1.901 ^-0.075
tp @s[tag=aj.gfreddy.bone.left_hand] ^0.682 ^-2.263 ^0.06
tp @s[tag=aj.gfreddy.bone.right_arm] ^-0.337 ^-1.388 ^-0.075
tp @s[tag=aj.gfreddy.bone.right_lower_arm] ^-0.451 ^-1.901 ^-0.075
tp @s[tag=aj.gfreddy.bone.right_hand] ^-0.689 ^-2.261 ^0.052
tp @s[tag=aj.gfreddy.bone.head] ^0.075 ^-1.388 ^0.225
tp @s[tag=aj.gfreddy.bone.jaw] ^-0.006 ^-1.261 ^0.15
execute store result score .calc aj.i run data get entity @s Air
execute store result entity @s Air short 1 run scoreboard players add .calc aj.i 2