#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.gfreddy.bone.left_leg] Pose.Head set value [-137.5f,0f,0f]
data modify entity @s[tag=aj.gfreddy.bone.left_lower_leg] Pose.Head set value [-17.5f,-20f,0f]
data modify entity @s[tag=aj.gfreddy.bone.left_foot] Pose.Head set value [2.5f,-20f,0f]
data modify entity @s[tag=aj.gfreddy.bone.right_leg] Pose.Head set value [-137.5f,0f,0f]
data modify entity @s[tag=aj.gfreddy.bone.right_lower_leg] Pose.Head set value [-20f,15f,0f]
data modify entity @s[tag=aj.gfreddy.bone.right_foot] Pose.Head set value [2.5f,15f,0f]
data modify entity @s[tag=aj.gfreddy.bone.body] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.gfreddy.bone.left_arm] Pose.Head set value [0f,0f,77.5f]
data modify entity @s[tag=aj.gfreddy.bone.left_lower_arm] Pose.Head set value [0f,17.5f,57.5f]
data modify entity @s[tag=aj.gfreddy.bone.left_hand] Pose.Head set value [-171.239f,77.296f,4.946f]
data modify entity @s[tag=aj.gfreddy.bone.right_arm] Pose.Head set value [0f,0f,-77.5f]
data modify entity @s[tag=aj.gfreddy.bone.right_lower_arm] Pose.Head set value [-6.155f,-16.414f,-56.611f]
data modify entity @s[tag=aj.gfreddy.bone.right_hand] Pose.Head set value [-168.317f,-70.623f,-11.774f]
data modify entity @s[tag=aj.gfreddy.bone.head] Pose.Head set value [0f,5f,-35f]
data modify entity @s[tag=aj.gfreddy.bone.jaw] Pose.Head set value [27.5f,5f,-35f]
tp @s ~ ~ ~ ~ ~