#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.177 ^0.767 ^0.349 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.119 ^0.79 ^0.388 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.059 ^0.806 ^0.424 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.119 ^0.79 ^0.367 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.177 ^0.767 ^0.307 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.231 ^0.737 ^0.349 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.28 ^0.702 ^0.388 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.323 ^0.661 ^0.424 ~ ~