#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.059 ^0.806 ^0.424 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.119 ^0.79 ^0.367 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.177 ^0.767 ^0.307 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.231 ^0.737 ^0.349 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.28 ^0.702 ^0.388 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.323 ^0.661 ^0.424 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.28 ^0.702 ^0.367 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.231 ^0.737 ^0.307 ~ ~