#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/jumpscare/tree/eyelids_root_0-7
execute if score .this aj.frame matches 8..15 run function chica:animations/jumpscare/tree/eyelids_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^-0.28 ^0.702 ^0.367 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.231 ^0.737 ^0.307 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.177 ^0.767 ^0.349 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.119 ^0.79 ^0.388 ~ ~