#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/jumpscare/tree/eyes_root_0-7
execute if score .this aj.frame matches 8..15 run function chica:animations/jumpscare/tree/eyes_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^-0.239 ^0.653 ^0.366 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.196 ^0.684 ^0.306 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.15 ^0.709 ^0.348 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.1 ^0.729 ^0.387 ~ ~