#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.048 ^0.743 ^0.424 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.1 ^0.729 ^0.366 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.15 ^0.709 ^0.306 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.196 ^0.684 ^0.348 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.239 ^0.653 ^0.387 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.276 ^0.618 ^0.424 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.239 ^0.653 ^0.366 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.196 ^0.684 ^0.306 ~ ~