#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.023 ^0.344 ^0.368 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.023 ^0.344 ^0.305 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.023 ^0.344 ^0.243 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.023 ^0.344 ^0.284 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.023 ^0.344 ^0.326 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.023 ^0.344 ^0.368 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.023 ^0.344 ^0.305 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.023 ^0.344 ^0.243 ~ ~