#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.007 ^0.433 ^0.486 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.005 ^0.428 ^0.424 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.016 ^0.423 ^0.362 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.026 ^0.417 ^0.404 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.035 ^0.411 ^0.445 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.044 ^0.405 ^0.486 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.035 ^0.411 ^0.424 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.026 ^0.417 ^0.362 ~ ~