#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [35f,0f,-10f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [3.2143f,0.379f,-17.6061f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [19.7932f,0.6197f,-25.1787f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [36.0114f,0.6677f,-32.7003f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [3.1511f,0.4748f,-40.1493f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [35f,0f,-47.5f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [3.1511f,0.4748f,-40.1493f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [19.7614f,0.6677f,-32.7003f]