#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/jumpscare/tree/jaw_display_0-7
execute if score .this aj.frame matches 8..15 run function chica:animations/jumpscare/tree/jaw_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [3.1511f,0.4748f,-40.1493f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [19.7614f,0.6677f,-32.7003f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [36.0432f,0.6197f,-25.1787f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [3.2143f,0.379f,-17.6061f]