#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.623 ^-0.243 ^-0.086 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.624 ^-0.219 ^-0.18 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.624 ^-0.192 ^-0.272 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.624 ^-0.21 ^-0.211 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.624 ^-0.227 ^-0.149 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.623 ^-0.243 ^-0.086 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.624 ^-0.219 ^-0.18 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.624 ^-0.192 ^-0.272 ~ ~