#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.061 ^0.512 ^0.521 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.004 ^0.51 ^0.465 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.067 ^0.5 ^0.405 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.127 ^0.483 ^0.447 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.185 ^0.46 ^0.485 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.238 ^0.431 ^0.521 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.185 ^0.46 ^0.465 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.127 ^0.483 ^0.405 ~ ~