#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0.6559f,-48.6834f,89.9876f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-0.8467f,-52.2131f,90.3145f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-2.5602f,-55.7267f,90.8636f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-1.3913f,-53.3863f,90.4699f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-0.3253f,-51.0381f,90.1837f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [0.6559f,-48.6834f,89.9876f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-0.8467f,-52.2131f,90.3145f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-2.5602f,-55.7267f,90.8636f]