#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/jumpscare/tree/left_arm_display_0-7
execute if score .this aj.frame matches 8..15 run function chica:animations/jumpscare/tree/left_arm_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [16.1521f,-36.8413f,64.9303f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [16.9911f,-40.4373f,63.5689f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [16.4187f,-38.0414f,64.4897f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [15.8974f,-35.64f,65.3588f]