#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.067 ^0.5 ^0.447 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.004 ^0.51 ^0.486 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.061 ^0.512 ^0.521 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.004 ^0.51 ^0.465 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.067 ^0.5 ^0.405 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.127 ^0.483 ^0.447 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.185 ^0.46 ^0.485 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.238 ^0.431 ^0.521 ~ ~