#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [16.4187f,-38.0414f,64.4897f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [15.8974f,-35.64f,65.3588f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [15.4208f,-33.2338f,66.1825f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [16.1521f,-36.8413f,64.9303f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [16.9911f,-40.4373f,63.5689f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [16.4187f,-38.0414f,64.4897f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [15.8974f,-35.64f,65.3588f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [15.4208f,-33.2338f,66.1825f]