#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.148 ^0.704 ^0.348 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.098 ^0.724 ^0.387 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.047 ^0.738 ^0.424 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.098 ^0.724 ^0.366 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.148 ^0.704 ^0.306 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.193 ^0.679 ^0.348 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.235 ^0.649 ^0.387 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.272 ^0.614 ^0.424 ~ ~