#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.371 ^0.202 ^0.218 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.371 ^0.202 ^0.26 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.371 ^0.202 ^0.301 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.371 ^0.202 ^0.239 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.371 ^0.202 ^0.176 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.371 ^0.202 ^0.218 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.371 ^0.202 ^0.26 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.371 ^0.202 ^0.301 ~ ~