#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [29.488f,38.05f,-59.9306f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [28.575f,35.8636f,-61.4483f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [27.7163f,33.664f,-62.9005f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [29.0243f,36.9585f,-60.698f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [30.4625f,40.222f,-58.3403f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [29.488f,38.05f,-59.9306f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [28.575f,35.8636f,-61.4483f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [27.7163f,33.664f,-62.9005f]