#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.371 ^0.202 ^0.301 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.371 ^0.202 ^0.239 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.371 ^0.202 ^0.176 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.371 ^0.202 ^0.218 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.371 ^0.202 ^0.26 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.371 ^0.202 ^0.301 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.371 ^0.202 ^0.239 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.371 ^0.202 ^0.176 ~ ~