#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/jumpscare/tree/right_hand_display_0-7
execute if score .this aj.frame matches 8..15 run function chica:animations/jumpscare/tree/right_hand_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [17.5582f,47.9445f,-77.0387f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [17.7723f,51.3933f,-75.4151f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [17.624f,49.0955f,-76.5043f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [17.4974f,46.7922f,-77.567f]