#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [17.624f,49.0955f,-76.5043f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [17.4974f,46.7922f,-77.567f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [17.3895f,44.4835f,-78.6066f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [17.5582f,47.9445f,-77.0387f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [17.7723f,51.3933f,-75.4151f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [17.624f,49.0955f,-76.5043f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [17.4974f,46.7922f,-77.567f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [17.3895f,44.4835f,-78.6066f]