#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.614 ^-0.216 ^-0.08 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.62 ^-0.186 ^-0.169 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.625 ^-0.155 ^-0.257 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.622 ^-0.176 ^-0.198 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.619 ^-0.196 ^-0.14 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.614 ^-0.216 ^-0.08 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.62 ^-0.186 ^-0.169 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.625 ^-0.155 ^-0.257 ~ ~