#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/jumpscare/tree/right_arm_display_0-7
execute if score .this aj.frame matches 8..15 run function chica:animations/jumpscare/tree/right_arm_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [29.0243f,36.9585f,-60.698f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [30.4625f,40.222f,-58.3403f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [29.488f,38.05f,-59.9306f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [28.575f,35.8636f,-61.4483f]