#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.622 ^-0.176 ^-0.198 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.619 ^-0.196 ^-0.14 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.614 ^-0.216 ^-0.08 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.62 ^-0.186 ^-0.169 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.625 ^-0.155 ^-0.257 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.622 ^-0.176 ^-0.198 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.619 ^-0.196 ^-0.14 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.614 ^-0.216 ^-0.08 ~ ~