#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.27 ^0.404 ^0.445 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.218 ^0.442 ^0.484 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.161 ^0.473 ^0.521 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.218 ^0.442 ^0.463 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.27 ^0.404 ^0.403 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.317 ^0.361 ^0.444 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.357 ^0.315 ^0.483 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.39 ^0.265 ^0.521 ~ ~