#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.161 ^0.473 ^0.521 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.218 ^0.442 ^0.463 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.27 ^0.404 ^0.403 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.317 ^0.361 ^0.444 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.357 ^0.315 ^0.483 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.39 ^0.265 ^0.521 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.357 ^0.315 ^0.463 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.317 ^0.361 ^0.403 ~ ~