#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/show_stage/tree/left_hand_display_0-7
execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-65.9609f,87.7724f,112.9562f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-65.9609f,87.7724f,112.9562f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-65.9609f,87.7724f,112.9562f]