#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation .this aj.id = @s aj.id
execute as @e[type=minecraft:armor_stand,tag=aj.foxy.bone,distance=..5.988] if score @s aj.id = .this aj.id run function foxy:set_variant/zzz/execute/9
scoreboard players set #execute aj.i 1