#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.5 ^-0.657 ^1.813 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.5 ^-0.657 ^1.813 ~ ~