#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^1 ^0.022 ^-3.262 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^1 ^0.022 ^-3.262 ~ ~