#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^1 ^-0.332 ^-3.187 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^1 ^-0.332 ^-3.187 ~ ~