#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [44.5798f,-42.923f,7.7709f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [44.5798f,-42.923f,7.7709f]