#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.937 ^0.734 ^-3.206 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.937 ^0.734 ^-3.206 ~ ~