#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [10f,-52.5f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [10f,-52.5f,0f]