#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-2.214 ^0.71 ^1.682 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-2.214 ^0.71 ^1.682 ~ ~