#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [2.9968f,-17.4129f,0.2208f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [2.9968f,-17.4129f,0.2208f]