#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [7.9306f,67.7619f,80.0974f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [7.9306f,67.7619f,80.0974f]