#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.backstage.bone.static] run function backstage:animations/easter_egg/tree/static_root_top
execute if entity @s[tag=aj.backstage.bone.head_bonnie_table] run function backstage:animations/easter_egg/tree/head_bonnie_table_root_top
execute if entity @s[tag=aj.backstage.bone.jaw] run function backstage:animations/easter_egg/tree/jaw_root_top
execute if entity @s[tag=aj.backstage.bone.bonnie_static] run function backstage:animations/easter_egg/tree/bonnie_static_root_top
execute if entity @s[tag=aj.backstage.bone.jaw2] run function backstage:animations/easter_egg/tree/jaw2_root_top
execute if entity @s[tag=aj.backstage.bone.bonnie_static2] run function backstage:animations/easter_egg/tree/bonnie_static2_root_top
execute if entity @s[tag=aj.backstage.bone.jaw3] run function backstage:animations/easter_egg/tree/jaw3_root_top
execute if entity @s[tag=aj.backstage.bone.head_bonnie] run function backstage:animations/easter_egg/tree/head_bonnie_root_top
execute if entity @s[tag=aj.backstage.bone.jaw4] run function backstage:animations/easter_egg/tree/jaw4_root_top
execute if entity @s[tag=aj.backstage.bone.head_chica] run function backstage:animations/easter_egg/tree/head_chica_root_top
execute if entity @s[tag=aj.backstage.bone.jaw6] run function backstage:animations/easter_egg/tree/jaw6_root_top
execute if entity @s[tag=aj.backstage.bone.chica_static] run function backstage:animations/easter_egg/tree/chica_static_root_top
execute if entity @s[tag=aj.backstage.bone.head_freddy] run function backstage:animations/easter_egg/tree/head_freddy_root_top
execute if entity @s[tag=aj.backstage.bone.eyes] run function backstage:animations/easter_egg/tree/eyes_root_top
execute if entity @s[tag=aj.backstage.bone.jaw7] run function backstage:animations/easter_egg/tree/jaw7_root_top
execute if entity @s[tag=aj.backstage.bone.pupils] run function backstage:animations/easter_egg/tree/pupils_root_top
execute if entity @s[tag=aj.backstage.bone.eyelids] run function backstage:animations/easter_egg/tree/eyelids_root_top
execute if entity @s[tag=aj.backstage.bone.head_freddy2] run function backstage:animations/easter_egg/tree/head_freddy2_root_top
execute if entity @s[tag=aj.backstage.bone.eyelids2] run function backstage:animations/easter_egg/tree/eyelids2_root_top
execute if entity @s[tag=aj.backstage.bone.pupils2] run function backstage:animations/easter_egg/tree/pupils2_root_top
execute if entity @s[tag=aj.backstage.bone.eyes2] run function backstage:animations/easter_egg/tree/eyes2_root_top
execute if entity @s[tag=aj.backstage.bone.jaw8] run function backstage:animations/easter_egg/tree/jaw8_root_top
execute if entity @s[tag=aj.backstage.bone.head_freddy3] run function backstage:animations/easter_egg/tree/head_freddy3_root_top
execute if entity @s[tag=aj.backstage.bone.jaw9] run function backstage:animations/easter_egg/tree/jaw9_root_top
execute if entity @s[tag=aj.backstage.bone.head] run function backstage:animations/easter_egg/tree/head_root_top
execute if entity @s[tag=aj.backstage.bone.jaw10] run function backstage:animations/easter_egg/tree/jaw10_root_top
execute if entity @s[tag=aj.backstage.bone.body] run function backstage:animations/easter_egg/tree/body_root_top
execute if entity @s[tag=aj.backstage.bone.left_arm] run function backstage:animations/easter_egg/tree/left_arm_root_top
execute if entity @s[tag=aj.backstage.bone.left_hand] run function backstage:animations/easter_egg/tree/left_hand_root_top
execute if entity @s[tag=aj.backstage.bone.right_hand] run function backstage:animations/easter_egg/tree/right_hand_root_top
execute if entity @s[tag=aj.backstage.bone.right_arm] run function backstage:animations/easter_egg/tree/right_arm_root_top
execute if entity @s[tag=aj.backstage.bone.left_lower_leg] run function backstage:animations/easter_egg/tree/left_lower_leg_root_top
execute if entity @s[tag=aj.backstage.bone.left_leg] run function backstage:animations/easter_egg/tree/left_leg_root_top
execute if entity @s[tag=aj.backstage.bone.right_lower_leg] run function backstage:animations/easter_egg/tree/right_lower_leg_root_top
execute if entity @s[tag=aj.backstage.bone.right_leg] run function backstage:animations/easter_egg/tree/right_leg_root_top
execute store result entity @s Air short 1 run scoreboard players get .this aj.frame