#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.bonnie.door.loopMode matches 0 run function bonnie:animations/door/stop
execute if score @s aj.bonnie.door.loopMode matches 1 run function bonnie:animations/door/pause
execute if score @s aj.bonnie.door.loopMode matches 2 run function bonnie:animations/door/zzz/execute/140