#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.freddy.powerout.loopMode matches 0 run function freddy:animations/powerout/stop
execute if score @s aj.freddy.powerout.loopMode matches 1 run function freddy:animations/powerout/pause
execute if score @s aj.freddy.powerout.loopMode matches 2 run function freddy:animations/powerout/zzz/execute/126