#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.bonnie.anim.w_hall_corner_twitching
execute if score .aj.anim_loop aj.bonnie.animating matches 0 run function bonnie:animation_loop
scoreboard players set #execute aj.i 1