#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [-20f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-11.6667f,0f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-3.3333f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [5f,0f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-3.3333f,0f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-11.6667f,0f,0f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-20f,0f,0f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-11.6667f,0f,0f]