#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.681 ^-0.107 ^0.185 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.705 ^-0.107 ^0.184 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.727 ^-0.064 ^0.182 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.748 ^-0.02 ^0.18 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.732 ^-0.017 ^0.182 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.716 ^-0.054 ^0.183 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.699 ^-0.091 ^0.185 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.699 ^-0.112 ^0.185 ~ ~