#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.748 ^0.001 ^0.18 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.716 ^-0.055 ^0.183 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.681 ^-0.107 ^0.185 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.705 ^-0.107 ^0.184 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.727 ^-0.064 ^0.182 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.748 ^-0.02 ^0.18 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.727 ^-0.022 ^0.182 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.705 ^-0.065 ^0.184 ~ ~