#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.35 ^0.283 ^0 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.35 ^0.262 ^0 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.35 ^0.283 ^0 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.35 ^0.304 ^0 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.35 ^0.325 ^0 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.35 ^0.304 ^0 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.35 ^0.283 ^0 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.35 ^0.262 ^0 ~ ~