#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-1.4876f,19.928f,49.6882f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-2.6785f,19.7371f,46.1542f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-3.8695f,19.5461f,42.6201f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-5.0604f,19.3552f,39.0861f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-4.1708f,19.5179f,41.7345f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-3.2812f,19.6806f,44.3828f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-2.3915f,19.8434f,47.0312f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-2.3915f,19.8434f,47.0312f]