#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.153 ^-1.271 ^-0.051 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.153 ^-1.178 ^-0.331 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.153 ^-1.227 ^-0.235 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.153 ^-1.259 ^-0.131 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.153 ^-1.273 ^-0.023 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.153 ^-1.251 ^0.165 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.153 ^-1.173 ^0.338 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.153 ^-1.048 ^0.479 ~ ~