#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [32.5f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [22.5f,0f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [12.5f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [2.5f,0f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-15f,0f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-32.5f,0f,0f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-50f,0f,0f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-22.5f,0f,0f]