#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [63.5915f,66.4354f,66.2491f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [67.5866f,65.8779f,74.6082f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [71.4086f,65.2391f,82.7843f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [68.8803f,65.6736f,77.3544f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [66.2737f,66.0731f,71.8417f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [63.5915f,66.4354f,66.2491f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [66.2737f,66.0731f,71.8417f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [68.8803f,65.6736f,77.3544f]