#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [32.5f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [35f,0f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [37.5f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [40f,0f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [40.8333f,0f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [41.6667f,0f,0f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [42.5f,0f,0f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [39.1667f,0f,0f]