#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [71.4086f,65.2391f,82.7843f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [68.8803f,65.6736f,77.3544f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [66.2737f,66.0731f,71.8417f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [63.5915f,66.4354f,66.2491f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [65.626f,66.186f,70.4645f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [67.6206f,65.915f,74.6373f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [69.5736f,65.6233f,78.7658f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [69.5736f,65.6233f,78.7658f]