#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.153 ^-1.178 ^-0.331 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.153 ^-1.227 ^-0.235 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.153 ^-1.259 ^-0.131 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.153 ^-1.273 ^-0.023 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.153 ^-1.251 ^0.165 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.153 ^-1.173 ^0.338 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.153 ^-1.048 ^0.479 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.153 ^-1.224 ^0.242 ~ ~