#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.156 ^-1.213 ^0.272 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.156 ^-0.986 ^0.527 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.156 ^-1.141 ^0.388 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.156 ^-1.241 ^0.205 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.156 ^-1.275 ^0 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.156 ^-1.261 ^-0.135 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.156 ^-1.217 ^-0.264 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.156 ^-1.146 ^-0.38 ~ ~