#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.156 ^-0.986 ^0.527 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.156 ^-1.141 ^0.388 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.156 ^-1.241 ^0.205 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.156 ^-1.275 ^0 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.156 ^-1.261 ^-0.135 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.156 ^-1.217 ^-0.264 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.156 ^-1.146 ^-0.38 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.156 ^-1.272 ^-0.064 ~ ~