#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [93.4814f,-27.4487f,95.7162f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [92.1079f,-28.6227f,94.5192f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [90.6661f,-29.7506f,93.3769f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [92.1454f,-28.6602f,94.5017f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [93.5588f,-27.5212f,95.6814f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [94.9065f,-26.3366f,96.9148f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [93.5588f,-27.5212f,95.6814f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [92.1454f,-28.6602f,94.5017f]