#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [4.5662f,-42.3005f,-49.2673f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [2.2811f,-42.3504f,-45.8819f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-0.0039f,-42.4002f,-42.4964f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-2.2889f,-42.45f,-39.111f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-0.0039f,-42.4002f,-42.4964f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [2.2811f,-42.3504f,-45.8819f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [4.5662f,-42.3005f,-49.2673f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [4.5662f,-42.3005f,-49.2673f]