#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.door_right.anim.close] at @s run function door_right:animations/close/next_frame
execute if entity @s[tag=aj.door_right.anim.open] at @s run function door_right:animations/open/next_frame
scoreboard players operation @s aj.door_right.animating = .aj.animation aj.door_right.animating