#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.right_door.bone.wall] run function right_door:animations/close/tree/wall_display_top
execute if entity @s[tag=aj.right_door.bone.door] run function right_door:animations/close/tree/door_display_top
execute positioned as @s run tp @s ~ ~ ~ ~ ~