#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function right_door:animations/close/tree/door_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^0 ^-1.913 ^0 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^-1.913 ^0 ~ ~