#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.left_door.bone.wall] run function left_door:animations/open/tree/wall_display_top
execute if entity @s[tag=aj.left_door.bone.door] run function left_door:animations/open/tree/door_display_top
execute positioned as @s run tp @s ~ ~ ~ ~ ~