#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function left_door:animations/open/tree/door_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^0 ^1.525 ^0 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^1.525 ^0 ~ ~