#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[type=minecraft:area_effect_cloud] run function left_door:animations/open/tree/root_bone_name
execute if entity @s[type=minecraft:armor_stand] run function left_door:animations/open/tree/display_bone_name