#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.freddy.restrooms.loopMode matches 0 run function freddy:animations/restrooms/stop
execute if score @s aj.freddy.restrooms.loopMode matches 1 run function freddy:animations/restrooms/pause
execute if score @s aj.freddy.restrooms.loopMode matches 2 run function freddy:animations/restrooms/zzz/execute/121