#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.freddy.anim.show_stage] at @s run function freddy:animations/show_stage/next_frame
execute if entity @s[tag=aj.freddy.anim.show_stage_alone] at @s run function freddy:animations/show_stage_alone/next_frame
execute if entity @s[tag=aj.freddy.anim.dining_area] at @s run function freddy:animations/dining_area/next_frame
execute if entity @s[tag=aj.freddy.anim.restrooms] at @s run function freddy:animations/restrooms/next_frame
execute if entity @s[tag=aj.freddy.anim.east_hall] at @s run function freddy:animations/east_hall/next_frame
execute if entity @s[tag=aj.freddy.anim.e_hall_corner] at @s run function freddy:animations/e_hall_corner/next_frame
execute if entity @s[tag=aj.freddy.anim.jumpscare_powerout] at @s run function freddy:animations/jumpscare_powerout/next_frame
execute if entity @s[tag=aj.freddy.anim.jumpscare_office] at @s run function freddy:animations/jumpscare_office/next_frame
execute if entity @s[tag=aj.freddy.anim.powerout] at @s run function freddy:animations/powerout/next_frame
scoreboard players operation @s aj.freddy.animating = .aj.animation aj.freddy.animating