#Project generated by Animated Java (https://animated-java.dev/)

tp @s[tag=aj.freddy.bone.left_leg] ^0.194 ^-0.713 ^-0.081
tp @s[tag=aj.freddy.bone.left_lower_leg] ^0.2 ^-1.182 ^-0.081
tp @s[tag=aj.freddy.bone.right_leg] ^-0.194 ^-0.713 ^-0.075
tp @s[tag=aj.freddy.bone.right_lower_leg] ^-0.194 ^-1.182 ^-0.075
tp @s[tag=aj.freddy.bone.body] ^0 ^-0.707 ^0
tp @s[tag=aj.freddy.bone.left_arm] ^0.356 ^0.231 ^-0.081
tp @s[tag=aj.freddy.bone.left_hand] ^0.906 ^0.237 ^-0.081
tp @s[tag=aj.freddy.bone.right_arm] ^-0.356 ^0.231 ^-0.081
tp @s[tag=aj.freddy.bone.right_hand] ^-0.906 ^0.231 ^-0.081
tp @s[tag=aj.freddy.bone.head] ^0 ^0.437 ^-0.062
tp @s[tag=aj.freddy.bone.eyes] ^0 ^0.862 ^-0.062
tp @s[tag=aj.freddy.bone.eyelids] ^0 ^0.862 ^-0.062
tp @s[tag=aj.freddy.bone.pupils] ^0 ^0.862 ^-0.062
tp @s[tag=aj.freddy.bone.jaw] ^0 ^0.549 ^-0.094
execute store result score .calc aj.i run data get entity @s Air
execute store result entity @s Air short 1 run scoreboard players add .calc aj.i 2