#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.door_right.anim.open
execute if score .aj.anim_loop aj.door_right.animating matches 0 run function door_right:animation_loop
scoreboard players set #execute aj.i 1