#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.chica.root] rotated ~ 0 run function chica:zzz/conditional/32
execute if score #execute aj.i matches 0 run function chica:zzz/conditional/33