#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.chica.root] at @s rotated ~ 0 run function chica:zzz/conditional/30
execute if score #execute aj.i matches 0 run function chica:zzz/conditional/31