#Project generated by Animated Java (https://animated-java.dev/)

schedule function freddy:animation_loop 1t
scoreboard players set .aj.anim_loop aj.freddy.animating 1
scoreboard players set .aj.animation aj.freddy.animating 0
execute as @e[type=minecraft:marker,tag=aj.freddy.root] run function freddy:zzz/execute/116
execute if score .aj.animation aj.freddy.animating matches 0 run function freddy:zzz/execute/117