#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.freddy.root] at @s rotated ~ 0 run function freddy:zzz/conditional/44
execute if score #execute aj.i matches 0 run function freddy:zzz/conditional/45