#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-2.1 ^-1.882 ^0.438 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-2.1 ^-1.882 ^0.438 ~ ~