#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-2.125 ^-0.469 ^1.438 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-2.125 ^-0.469 ^1.438 ~ ~