#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.527 ^0.394 ^-2.858 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.527 ^0.394 ^-2.858 ~ ~