#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [50f,35f,87.5f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [50f,35f,87.5f]