#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [-101.5461f,-49.2148f,-63.8577f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-101.5461f,-49.2148f,-63.8577f]