#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.door_right.open.loopMode matches 0 run function door_right:animations/open/stop
execute if score @s aj.door_right.open.loopMode matches 1 run function door_right:animations/open/pause
execute if score @s aj.door_right.open.loopMode matches 2 run function door_right:animations/open/zzz/execute/20