#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.chica.east_hall1.loopMode matches 0 run function chica:animations/east_hall1/stop
execute if score @s aj.chica.east_hall1.loopMode matches 1 run function chica:animations/east_hall1/pause
execute if score @s aj.chica.east_hall1.loopMode matches 2 run function chica:animations/east_hall1/zzz/execute/99