#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.freddy.root] at @s run function freddy:animations/show_stage_alone/zzz/conditional/60
execute if score #execute aj.i matches 0 run function freddy:animations/show_stage_alone/zzz/conditional/61