#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [13.3341f,14.4397f,-21.0339f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [8.6567f,14.4691f,-19.7432f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [3.9794f,14.4984f,-18.4526f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-0.6979f,14.5277f,-17.162f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [2.7294f,14.4984f,-18.4526f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [6.1567f,14.4691f,-19.7432f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [9.5841f,14.4397f,-21.0339f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [13.0114f,14.4104f,-22.3245f]