#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function freddy:animations/jumpscare_office/tree/body_display_0-7
execute if score .this aj.frame matches 8..15 run function freddy:animations/jumpscare_office/tree/body_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [10.3503f,14.4397f,-22.9692f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [7.6891f,14.4691f,-23.614f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [5.028f,14.4984f,-24.2588f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [2.3669f,14.5277f,-24.9035f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [2.3669f,14.5277f,-24.9035f]