#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [-74.087f,12.5208f,-21.2365f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-60.9301f,12.7907f,-21.3919f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-47.7732f,13.0607f,-21.5473f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-34.6162f,13.3306f,-21.7027f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-21.4593f,13.6006f,-21.8582f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-8.3024f,13.8705f,-22.0136f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [4.8545f,14.1405f,-22.169f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [18.0114f,14.4104f,-22.3245f]