#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function freddy:animations/jumpscare_office/tree/eyelids_root_0-7
execute if score .this aj.frame matches 8..15 run function freddy:animations/jumpscare_office/tree/eyelids_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^-0.615 ^0.768 ^0.395 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.684 ^0.761 ^0.296 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.745 ^0.738 ^0.195 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.745 ^0.74 ^0.133 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.745 ^0.74 ^0.133 ~ ~