#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.188 ^-0.243 ^-1.547 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.027 ^0.104 ^-1.413 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.14 ^0.399 ^-1.19 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.302 ^0.624 ^-0.893 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.449 ^0.764 ^-0.541 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.491 ^0.834 ^-0.17 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.504 ^0.811 ^0.207 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.483 ^0.701 ^0.562 ~ ~