#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.178 ^-0.254 ^-1.486 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.024 ^0.077 ^-1.357 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.135 ^0.358 ^-1.143 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.29 ^0.573 ^-0.86 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.43 ^0.707 ^-0.524 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.478 ^0.773 ^-0.168 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.497 ^0.751 ^0.193 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.484 ^0.645 ^0.534 ~ ~