#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.461 ^0.308 ^0.266 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.422 ^0.343 ^0.188 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.38 ^0.369 ^0.108 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.334 ^0.387 ^0.028 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.375 ^0.373 ^0.105 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.413 ^0.353 ^0.181 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.449 ^0.329 ^0.257 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.483 ^0.3 ^0.333 ~ ~