#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.48 ^0.423 ^0.276 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.463 ^0.452 ^0.182 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.44 ^0.467 ^0.086 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.41 ^0.468 ^-0.009 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.426 ^0.475 ^0.083 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.435 ^0.468 ^0.175 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.438 ^0.445 ^0.265 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.492 ^0.416 ^0.34 ~ ~