#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [-59.087f,12.5208f,-21.2365f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-42.1801f,12.7907f,-21.3919f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-25.2732f,13.0607f,-21.5473f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-4.6162f,13.3306f,-21.7027f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [16.0407f,13.6006f,-21.8582f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [31.3704f,14.243f,-12.5688f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [46.1635f,10.3842f,-3.7954f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [59.3223f,2.632f,2.855f]