#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function freddy:animations/jumpscare_office/tree/jaw_display_0-7
execute if score .this aj.frame matches 8..15 run function freddy:animations/jumpscare_office/tree/jaw_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [46.0998f,11.6362f,-13.1109f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [38.4558f,14.2117f,-22.3495f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [30.5282f,15.6771f,-31.9306f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [27.8745f,15.3612f,-32.6185f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [27.8745f,15.3612f,-32.6185f]