#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function freddy:animations/jumpscare_office/tree/jaw_root_0-7
execute if score .this aj.frame matches 8..15 run function freddy:animations/jumpscare_office/tree/jaw_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^-0.511 ^0.423 ^0.286 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.528 ^0.425 ^0.232 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.542 ^0.421 ^0.178 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.542 ^0.423 ^0.132 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.542 ^0.423 ^0.132 ~ ~