#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [51.3997f,10.0277f,-8.3781f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [41.8917f,14.748f,-21.0036f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [31.7095f,16.3192f,-34.5586f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [25.6683f,14.6876f,-48.1885f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [35.521f,15.6436f,-29.614f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [45.7114f,12.7309f,-11.3556f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [54.4758f,6.2341f,5.6796f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [53.25f,8.0478f,-4.3261f]