#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.139 ^-0.337 ^-1.186 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.022 ^-0.085 ^-1.088 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.099 ^0.132 ^-0.929 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.218 ^0.302 ^-0.718 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.328 ^0.415 ^-0.467 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.404 ^0.468 ^-0.193 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.459 ^0.456 ^0.09 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.49 ^0.38 ^0.365 ~ ~