#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function freddy:animations/jumpscare_office/tree/left_hand_display_0-7
execute if score .this aj.frame matches 8..15 run function freddy:animations/jumpscare_office/tree/left_hand_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [40.1655f,7.8787f,53.9966f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [40.7855f,11.2967f,51.3875f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [41.1636f,14.6657f,48.6809f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [41.2863f,17.9702f,45.8511f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [41.2863f,17.9702f,45.8511f]