#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function freddy:animations/jumpscare_office/tree/left_leg_root_0-7
execute if score .this aj.frame matches 8..15 run function freddy:animations/jumpscare_office/tree/left_leg_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0.194 ^-0.713 ^0.013 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.194 ^-0.713 ^0.023 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.194 ^-0.713 ^0.033 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.194 ^-0.713 ^0.044 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.194 ^-0.713 ^0.044 ~ ~