#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function freddy:animations/jumpscare_office/tree/left_arm_display_0-7
execute if score .this aj.frame matches 8..15 run function freddy:animations/jumpscare_office/tree/left_arm_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [29.2032f,-6.4995f,9.5468f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [27.2405f,-3.6298f,7.0077f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [25.146f,-0.9639f,4.3001f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [22.9181f,1.4796f,1.4257f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [22.9181f,1.4796f,1.4257f]