#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.194 ^-0.713 ^-0.071 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.194 ^-0.713 ^-0.06 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.194 ^-0.713 ^-0.05 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.194 ^-0.713 ^-0.04 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.194 ^-0.713 ^-0.029 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.194 ^-0.713 ^-0.019 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.194 ^-0.713 ^-0.008 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.194 ^-0.713 ^0.002 ~ ~