#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.069 ^0.329 ^0.246 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.03 ^0.346 ^0.178 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.012 ^0.355 ^0.109 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.057 ^0.356 ^0.041 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.018 ^0.356 ^0.109 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.02 ^0.352 ^0.177 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.057 ^0.342 ^0.245 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.091 ^0.329 ^0.313 ~ ~