#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function freddy:animations/jumpscare_office/tree/left_arm_root_0-7
execute if score .this aj.frame matches 8..15 run function freddy:animations/jumpscare_office/tree/left_arm_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^-0.095 ^0.337 ^0.279 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.097 ^0.344 ^0.245 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.099 ^0.349 ^0.21 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.1 ^0.352 ^0.176 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.1 ^0.352 ^0.176 ~ ~