#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.557 ^0.696 ^0.411 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.596 ^0.72 ^0.277 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.623 ^0.717 ^0.14 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.643 ^0.675 ^0.002 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.592 ^0.733 ^0.134 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.521 ^0.75 ^0.269 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.437 ^0.724 ^0.395 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.534 ^0.693 ^0.466 ~ ~