#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.167 ^-0.258 ^-1.489 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.013 ^0.072 ^-1.36 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.147 ^0.354 ^-1.146 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.301 ^0.568 ^-0.863 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.442 ^0.702 ^-0.527 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.49 ^0.77 ^-0.172 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.51 ^0.75 ^0.19 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.497 ^0.646 ^0.534 ~ ~