#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function freddy:animations/jumpscare_office/tree/pupils_root_0-7
execute if score .this aj.frame matches 8..15 run function freddy:animations/jumpscare_office/tree/pupils_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^-0.591 ^0.705 ^0.382 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.642 ^0.704 ^0.294 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.689 ^0.692 ^0.205 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.689 ^0.694 ^0.145 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.689 ^0.694 ^0.145 ~ ~