#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.713 ^0.082 ^0.068 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.679 ^0.113 ^0 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.642 ^0.137 ^-0.069 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.602 ^0.153 ^-0.138 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.637 ^0.138 ^-0.07 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.67 ^0.118 ^-0.001 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.701 ^0.095 ^0.068 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.73 ^0.067 ^0.136 ~ ~