#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [-69.5111f,-17.9624f,-40.9939f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-57.3537f,-12.7159f,-47.2747f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-46.0405f,-6.3789f,-52.2706f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-35.3761f,0.7492f,-55.9681f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-25.0768f,8.3985f,-58.3745f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-14.7991f,16.3219f,-59.4558f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-4.1362f,24.2744f,-59.091f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [7.4036f,31.9819f,-57.0368f]