#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function freddy:animations/jumpscare_office/tree/right_arm_root_0-7
execute if score .this aj.frame matches 8..15 run function freddy:animations/jumpscare_office/tree/right_arm_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^-0.73 ^0.068 ^0.102 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.73 ^0.068 ^0.067 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.728 ^0.066 ^0.032 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.726 ^0.062 ^-0.003 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.726 ^0.062 ^-0.003 ~ ~