#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function freddy:animations/jumpscare_office/tree/right_arm_display_0-7
execute if score .this aj.frame matches 8..15 run function freddy:animations/jumpscare_office/tree/right_arm_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-1.5439f,27.5949f,-63.4824f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-2.2283f,26.1154f,-60.9861f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-3.0752f,24.8206f,-58.5131f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-5.422f,23.3891f,-59.4495f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-5.422f,23.3891f,-59.4495f]