#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.194 ^-1.182 ^-0.065 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.194 ^-1.182 ^-0.054 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.194 ^-1.182 ^-0.044 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.194 ^-1.182 ^-0.033 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.194 ^-1.182 ^-0.023 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.194 ^-1.182 ^-0.012 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.194 ^-1.182 ^-0.002 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.194 ^-1.182 ^0.008 ~ ~