#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function freddy:animations/jumpscare_office/tree/right_leg_root_0-7
execute if score .this aj.frame matches 8..15 run function freddy:animations/jumpscare_office/tree/right_leg_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^-0.194 ^-0.713 ^0.019 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.194 ^-0.713 ^0.029 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.194 ^-0.713 ^0.04 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.194 ^-0.713 ^0.05 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.194 ^-0.713 ^0.05 ~ ~