#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.591 ^-0.916 ^-0.868 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.65 ^-0.768 ^-0.849 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.715 ^-0.631 ^-0.794 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.781 ^-0.515 ^-0.707 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.846 ^-0.424 ^-0.593 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.905 ^-0.364 ^-0.458 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.957 ^-0.338 ^-0.31 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.997 ^-0.348 ^-0.155 ~ ~