#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function freddy:animations/jumpscare_office/tree/right_hand_display_0-7
execute if score .this aj.frame matches 8..15 run function freddy:animations/jumpscare_office/tree/right_hand_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [5.115f,10.8503f,-92.8832f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [5.3075f,9.2611f,-90.0441f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [5.2629f,7.758f,-87.2135f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [4.0468f,5.4823f,-87.3315f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [4.0468f,5.4823f,-87.3315f]