#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.196 ^-0.573 ^-1.038 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.286 ^-0.373 ^-0.97 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.38 ^-0.199 ^-0.855 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.473 ^-0.059 ^-0.7 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.56 ^0.039 ^-0.513 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.637 ^0.09 ^-0.304 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.699 ^0.092 ^-0.083 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.743 ^0.043 ^0.136 ~ ~