#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [-17.5f,-20f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-17.5f,-20f,0f]