#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [-6.1549f,-16.4137f,-56.6115f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-6.1549f,-16.4137f,-56.6115f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-6.1549f,-16.4137f,-56.6115f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-6.1549f,-16.4137f,-56.6115f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-6.1549f,-16.4137f,-56.6115f]