#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set # aj.i 1
execute at @s as @e[type=#right_door:bone_entities,tag=aj.right_door.bone] if score @s aj.id = .this aj.id run function right_door:zzz/execute/11