#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[type=minecraft:area_effect_cloud] run function foxy:zzz/execute/20
execute if entity @s[type=minecraft:armor_stand] run tp @s ~ ~ ~ ~ ~