#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set # aj.i 1
execute at @s as @e[type=#foxy:bone_entities,tag=aj.foxy.bone] if score @s aj.id = .this aj.id run function foxy:zzz/execute/22