#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.foxy.anim.stage_0] at @s run function foxy:animations/stage_0/next_frame
execute if entity @s[tag=aj.foxy.anim.stage_1] at @s run function foxy:animations/stage_1/next_frame
execute if entity @s[tag=aj.foxy.anim.stage_2] at @s run function foxy:animations/stage_2/next_frame
execute if entity @s[tag=aj.foxy.anim.running] at @s run function foxy:animations/running/next_frame
execute if entity @s[tag=aj.foxy.anim.jumpscare] at @s run function foxy:animations/jumpscare/next_frame
scoreboard players operation @s aj.foxy.animating = .aj.animation aj.foxy.animating