#Project generated by Animated Java (https://animated-java.dev/)

tp @s[tag=aj.foxy.bone.left_leg] ^0.15 ^-0.65 ^0
tp @s[tag=aj.foxy.bone.left_lower_leg] ^0.153 ^-1.273 ^0.004
tp @s[tag=aj.foxy.bone.right_leg] ^-0.156 ^-0.65 ^0
tp @s[tag=aj.foxy.bone.right_lower_leg] ^-0.156 ^-1.275 ^0
tp @s[tag=aj.foxy.bone.body] ^0 ^-0.625 ^0
tp @s[tag=aj.foxy.bone.head] ^0 ^0.437 ^0
tp @s[tag=aj.foxy.bone.jaw] ^0 ^0.587 ^0
tp @s[tag=aj.foxy.bone.eyepatch] ^-0.116 ^0.977 ^0.233
tp @s[tag=aj.foxy.bone.left_arm] ^0.35 ^0.2 ^0
tp @s[tag=aj.foxy.bone.left_hand] ^0.894 ^0.2 ^0
tp @s[tag=aj.foxy.bone.right_arm] ^-0.35 ^0.2 ^0
tp @s[tag=aj.foxy.bone.right_hand] ^-0.894 ^0.2 ^0
execute store result score .calc aj.i run data get entity @s Air
execute store result entity @s Air short 1 run scoreboard players add .calc aj.i 2