#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if score @s aj.frame matches ..1 run function chica:animations/e_hall_corner_twitching/zzz/conditional/102
execute if score #execute aj.i matches 0 run function chica:animations/e_hall_corner_twitching/zzz/conditional/103