#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.right_door.anim.open
execute if score .aj.anim_loop aj.right_door.animating matches 0 run function right_door:animation_loop
scoreboard players set #execute aj.i 1