#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.chica.dining_area2.loopMode matches 0 run function chica:animations/dining_area2/stop
execute if score @s aj.chica.dining_area2.loopMode matches 1 run function chica:animations/dining_area2/pause
execute if score @s aj.chica.dining_area2.loopMode matches 2 run function chica:animations/dining_area2/zzz/execute/98