#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/east_hall2/tree/jaw_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^-0.057 ^0.568 ^0.097 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.057 ^0.568 ^0.097 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.057 ^0.568 ^0.097 ~ ~