#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/east_hall2/tree/left_hand_display_0-7
execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [7.6734f,26.4883f,81.8086f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [7.6734f,26.4883f,81.8086f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [7.6734f,26.4883f,81.8086f]