#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/east_hall2/tree/right_arm_display_0-7
execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [1.1069f,12.4517f,-62.3792f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [1.1069f,12.4517f,-62.3792f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [1.1069f,12.4517f,-62.3792f]