#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/east_hall2/tree/right_hand_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^-0.644 ^-0.25 ^-0.187 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.644 ^-0.25 ^-0.187 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.644 ^-0.25 ^-0.187 ~ ~