#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function chica:animations/east_hall2/tree/right_eyebrow_display_0-7
execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-10.5771f,13.5647f,-33.1902f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-10.5771f,13.5647f,-33.1902f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-10.5771f,13.5647f,-33.1902f]