#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.bonnie.root] run function bonnie:animations/backstage/zzz/conditional/110
execute if score #execute aj.i matches 0 run function bonnie:animations/backstage/zzz/conditional/111