#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/supply_closet/tree/pupils_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^-0.005 ^0.877 ^0.063 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.005 ^0.877 ^0.063 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.005 ^0.877 ^0.063 ~ ~