#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.foxy.root] at @s run function foxy:animations/jumpscare/zzz/conditional/50
execute if score #execute aj.i matches 0 run function foxy:animations/jumpscare/zzz/conditional/51