#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/show_stage/tree/guitar_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^0.369 ^0.043 ^0.794 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.369 ^0.043 ^0.794 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.369 ^0.043 ^0.794 ~ ~