#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/show_stage/tree/jaw_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^0 ^0.6 ^-0.21 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^0.6 ^-0.21 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^0.6 ^-0.21 ~ ~