#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/show_stage/tree/left_hand_display_0-7
execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [50.4105f,79.1914f,-129.8921f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [50.4105f,79.1914f,-129.8921f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [50.4105f,79.1914f,-129.8921f]