#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bonnie:animations/show_stage/tree/right_upper_ear_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^-0.162 ^1.582 ^0.156 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.162 ^1.582 ^0.156 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.162 ^1.582 ^0.156 ~ ~