#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.chica.door.loopMode matches 0 run function chica:animations/door/stop
execute if score @s aj.chica.door.loopMode matches 1 run function chica:animations/door/pause
execute if score @s aj.chica.door.loopMode matches 2 run function chica:animations/door/zzz/execute/105