#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.chica.root] at @s run function chica:animations/door/zzz/conditional/124
execute if score #execute aj.i matches 0 run function chica:animations/door/zzz/conditional/125