#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation # aj.id = @s aj.id
execute as @e[type=#freddy:bone_entities,tag=aj.freddy,distance=..5.648] if score @s aj.id = # aj.id run kill @s
kill @s
scoreboard players set #execute aj.i 1