#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.bonnie.guitar.loopMode matches 0 run function bonnie:animations/guitar/stop
execute if score @s aj.bonnie.guitar.loopMode matches 1 run function bonnie:animations/guitar/pause
execute if score @s aj.bonnie.guitar.loopMode matches 2 run function bonnie:animations/guitar/zzz/execute/142