#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function foxy:animations/stage_0/tree/eyepatch_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^-0.116 ^0.977 ^0.233 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.116 ^0.977 ^0.233 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.116 ^0.977 ^0.233 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.116 ^0.977 ^0.233 ~ ~