#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function foxy:animations/stage_0/tree/right_lower_leg_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^-0.156 ^-1.275 ^0 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.156 ^-1.275 ^0 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.156 ^-1.275 ^0 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.156 ^-1.275 ^0 ~ ~