#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.foxy.stage_0.loopMode matches 0 run function foxy:animations/stage_0/stop
execute if score @s aj.foxy.stage_0.loopMode matches 1 run function foxy:animations/stage_0/pause
execute if score @s aj.foxy.stage_0.loopMode matches 2 run function foxy:animations/stage_0/zzz/execute/30