#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.chica.e_hall_corner_twitching.loopMode matches 0 run function chica:animations/e_hall_corner_twitching/stop
execute if score @s aj.chica.e_hall_corner_twitching.loopMode matches 1 run function chica:animations/e_hall_corner_twitching/pause
execute if score @s aj.chica.e_hall_corner_twitching.loopMode matches 2 run function chica:animations/e_hall_corner_twitching/zzz/execute/102