#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.chica.root] run function chica:animations/e_hall_corner_twitching/zzz/conditional/100
execute if score #execute aj.i matches 0 run function chica:animations/e_hall_corner_twitching/zzz/conditional/101