#Project generated by Animated Java (https://animated-java.dev/)

tag @s remove aj.gfreddy.anim.idle
scoreboard players set @s aj.frame 0
scoreboard players operation .this aj.id = @s aj.id
execute as @e[type=minecraft:area_effect_cloud,tag=aj.gfreddy.bone,distance=..3.636] if score @s aj.id = .this aj.id run function gfreddy:zzz/execute/10
execute as @e[type=minecraft:armor_stand,tag=aj.gfreddy.bone,distance=..3.636] if score @s aj.id = .this aj.id run function gfreddy:zzz/execute/11
scoreboard players set #execute aj.i 1