#Project generated by Animated Java (https://animated-java.dev/)

schedule function door_right:animation_loop 1t
scoreboard players set .aj.anim_loop aj.door_right.animating 1
scoreboard players set .aj.animation aj.door_right.animating 0
execute as @e[type=minecraft:marker,tag=aj.door_right.root] run function door_right:zzz/execute/17
execute if score .aj.animation aj.door_right.animating matches 0 run function door_right:zzz/execute/18