#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players add .aj.animation aj.door_right.animating 0
scoreboard players add .aj.anim_loop aj.door_right.animating 0
scoreboard players add .noScripts aj.i 0