#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.door_right.root] rotated ~ 0 run function door_right:zzz/conditional/8
execute if score #execute aj.i matches 0 run function door_right:zzz/conditional/9