#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if score @s aj.frame matches ..1 run function freddy:animations/powerout/zzz/conditional/136
execute if score #execute aj.i matches 0 run function freddy:animations/powerout/zzz/conditional/137