#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.foxy.stage_2.loopMode matches 0 run function foxy:animations/stage_2/stop
execute if score @s aj.foxy.stage_2.loopMode matches 1 run function foxy:animations/stage_2/pause
execute if score @s aj.foxy.stage_2.loopMode matches 2 run function foxy:animations/stage_2/zzz/execute/32