#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation # aj.id = @s aj.id
execute as @e[type=#door_right:bone_entities,tag=aj.door_right,distance=..6.251] if score @s aj.id = # aj.id run kill @s
kill @s
scoreboard players set #execute aj.i 1