#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.freddy.jumpscare_office.loopMode matches 0 run function freddy:animations/jumpscare_office/stop
execute if score @s aj.freddy.jumpscare_office.loopMode matches 1 run function freddy:animations/jumpscare_office/pause
execute if score @s aj.freddy.jumpscare_office.loopMode matches 2 run function freddy:animations/jumpscare_office/zzz/execute/125