#Project generated by Animated Java (https://animated-java.dev/)

tp @s[tag=aj.left_door.bone.door] ^0 ^-1.913 ^0
tp @s[tag=aj.left_door.bone.wall] ^0 ^-1.913 ^0
execute store result score .calc aj.i run data get entity @s Air
execute store result entity @s Air short 1 run scoreboard players add .calc aj.i 2