#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[type=minecraft:area_effect_cloud] run function left_door:zzz/execute/15
execute if entity @s[type=minecraft:armor_stand] run tp @s ~ ~ ~ ~ ~