#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set # aj.i 1
execute at @s as @e[type=#left_door:bone_entities,tag=aj.left_door.bone] if score @s aj.id = .this aj.id run function left_door:zzz/execute/17