#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.chica.e_hall_corner.loopMode matches 0 run function chica:animations/e_hall_corner/stop
execute if score @s aj.chica.e_hall_corner.loopMode matches 1 run function chica:animations/e_hall_corner/pause
execute if score @s aj.chica.e_hall_corner.loopMode matches 2 run function chica:animations/e_hall_corner/zzz/execute/101