#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.backstage.easter_egg.loopMode matches 0 run function backstage:animations/easter_egg/stop
execute if score @s aj.backstage.easter_egg.loopMode matches 1 run function backstage:animations/easter_egg/pause
execute if score @s aj.backstage.easter_egg.loopMode matches 2 run function backstage:animations/easter_egg/zzz/execute/29