#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.backstage.root] at @s run function backstage:animations/easter_egg/zzz/conditional/26
execute if score #execute aj.i matches 0 run function backstage:animations/easter_egg/zzz/conditional/27