#Project generated by Animated Java (https://animated-java.dev/)

tag @s remove aj.freddy.anim.show_stage
tag @s remove aj.freddy.anim.show_stage_alone
tag @s remove aj.freddy.anim.dining_area
tag @s remove aj.freddy.anim.restrooms
tag @s remove aj.freddy.anim.east_hall
tag @s remove aj.freddy.anim.e_hall_corner
tag @s remove aj.freddy.anim.jumpscare_powerout
tag @s remove aj.freddy.anim.jumpscare_office
tag @s remove aj.freddy.anim.powerout
scoreboard players set @s aj.frame 0
scoreboard players operation .this aj.id = @s aj.id
execute as @e[type=minecraft:area_effect_cloud,tag=aj.freddy.bone,distance=..5.648] if score @s aj.id = .this aj.id run function freddy:zzz/execute/86
execute as @e[type=minecraft:armor_stand,tag=aj.freddy.bone,distance=..5.648] if score @s aj.id = .this aj.id run function freddy:zzz/execute/87
scoreboard players set #execute aj.i 1