#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.bonnie.bone.left_leg] ArmorItems[-1].tag.CustomModelData set value 133
data modify entity @s[tag=aj.bonnie.bone.left_lower_leg] ArmorItems[-1].tag.CustomModelData set value 134
data modify entity @s[tag=aj.bonnie.bone.right_leg] ArmorItems[-1].tag.CustomModelData set value 135
data modify entity @s[tag=aj.bonnie.bone.right_lower_leg] ArmorItems[-1].tag.CustomModelData set value 136
data modify entity @s[tag=aj.bonnie.bone.body] ArmorItems[-1].tag.CustomModelData set value 137
data modify entity @s[tag=aj.bonnie.bone.head] ArmorItems[-1].tag.CustomModelData set value 138
data modify entity @s[tag=aj.bonnie.bone.eyes] ArmorItems[-1].tag.CustomModelData set value 139
data modify entity @s[tag=aj.bonnie.bone.pupils] ArmorItems[-1].tag.CustomModelData set value 140
data modify entity @s[tag=aj.bonnie.bone.left_ear] ArmorItems[-1].tag.CustomModelData set value 142
data modify entity @s[tag=aj.bonnie.bone.left_upper_ear] ArmorItems[-1].tag.CustomModelData set value 143
data modify entity @s[tag=aj.bonnie.bone.right_ear] ArmorItems[-1].tag.CustomModelData set value 144
data modify entity @s[tag=aj.bonnie.bone.right_upper_ear] ArmorItems[-1].tag.CustomModelData set value 145
data modify entity @s[tag=aj.bonnie.bone.jaw] ArmorItems[-1].tag.CustomModelData set value 146
data modify entity @s[tag=aj.bonnie.bone.right_arm] ArmorItems[-1].tag.CustomModelData set value 147
data modify entity @s[tag=aj.bonnie.bone.right_hand] ArmorItems[-1].tag.CustomModelData set value 148
data modify entity @s[tag=aj.bonnie.bone.left_arm] ArmorItems[-1].tag.CustomModelData set value 149
data modify entity @s[tag=aj.bonnie.bone.left_hand] ArmorItems[-1].tag.CustomModelData set value 150
data modify entity @s[tag=aj.bonnie.bone.guitar] ArmorItems[-1].tag.CustomModelData set value 151
data modify entity @s[tag=aj.bonnie.bone.eyelids] ArmorItems[-1].tag.CustomModelData set value 141