#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.bonnie.bone.left_leg] ArmorItems[-1].tag.CustomModelData set value 227
data modify entity @s[tag=aj.bonnie.bone.left_lower_leg] ArmorItems[-1].tag.CustomModelData set value 228
data modify entity @s[tag=aj.bonnie.bone.right_leg] ArmorItems[-1].tag.CustomModelData set value 229
data modify entity @s[tag=aj.bonnie.bone.right_lower_leg] ArmorItems[-1].tag.CustomModelData set value 230
data modify entity @s[tag=aj.bonnie.bone.body] ArmorItems[-1].tag.CustomModelData set value 231
data modify entity @s[tag=aj.bonnie.bone.head] ArmorItems[-1].tag.CustomModelData set value 232
data modify entity @s[tag=aj.bonnie.bone.eyes] ArmorItems[-1].tag.CustomModelData set value 233
data modify entity @s[tag=aj.bonnie.bone.pupils] ArmorItems[-1].tag.CustomModelData set value 234
data modify entity @s[tag=aj.bonnie.bone.left_ear] ArmorItems[-1].tag.CustomModelData set value 236
data modify entity @s[tag=aj.bonnie.bone.left_upper_ear] ArmorItems[-1].tag.CustomModelData set value 237
data modify entity @s[tag=aj.bonnie.bone.right_ear] ArmorItems[-1].tag.CustomModelData set value 238
data modify entity @s[tag=aj.bonnie.bone.right_upper_ear] ArmorItems[-1].tag.CustomModelData set value 239
data modify entity @s[tag=aj.bonnie.bone.jaw] ArmorItems[-1].tag.CustomModelData set value 240
data modify entity @s[tag=aj.bonnie.bone.right_arm] ArmorItems[-1].tag.CustomModelData set value 241
data modify entity @s[tag=aj.bonnie.bone.right_hand] ArmorItems[-1].tag.CustomModelData set value 242
data modify entity @s[tag=aj.bonnie.bone.left_arm] ArmorItems[-1].tag.CustomModelData set value 243
data modify entity @s[tag=aj.bonnie.bone.left_hand] ArmorItems[-1].tag.CustomModelData set value 244
data modify entity @s[tag=aj.bonnie.bone.guitar] ArmorItems[-1].tag.CustomModelData set value 245
data modify entity @s[tag=aj.bonnie.bone.eyelids] ArmorItems[-1].tag.CustomModelData set value 235