#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.bonnie.bone.left_leg] ArmorItems[-1].tag.CustomModelData set value 246
data modify entity @s[tag=aj.bonnie.bone.left_lower_leg] ArmorItems[-1].tag.CustomModelData set value 247
data modify entity @s[tag=aj.bonnie.bone.right_leg] ArmorItems[-1].tag.CustomModelData set value 248
data modify entity @s[tag=aj.bonnie.bone.right_lower_leg] ArmorItems[-1].tag.CustomModelData set value 249
data modify entity @s[tag=aj.bonnie.bone.body] ArmorItems[-1].tag.CustomModelData set value 250
data modify entity @s[tag=aj.bonnie.bone.head] ArmorItems[-1].tag.CustomModelData set value 251
data modify entity @s[tag=aj.bonnie.bone.eyes] ArmorItems[-1].tag.CustomModelData set value 252
data modify entity @s[tag=aj.bonnie.bone.pupils] ArmorItems[-1].tag.CustomModelData set value 253
data modify entity @s[tag=aj.bonnie.bone.left_ear] ArmorItems[-1].tag.CustomModelData set value 255
data modify entity @s[tag=aj.bonnie.bone.left_upper_ear] ArmorItems[-1].tag.CustomModelData set value 256
data modify entity @s[tag=aj.bonnie.bone.right_ear] ArmorItems[-1].tag.CustomModelData set value 257
data modify entity @s[tag=aj.bonnie.bone.right_upper_ear] ArmorItems[-1].tag.CustomModelData set value 258
data modify entity @s[tag=aj.bonnie.bone.jaw] ArmorItems[-1].tag.CustomModelData set value 259
data modify entity @s[tag=aj.bonnie.bone.right_arm] ArmorItems[-1].tag.CustomModelData set value 260
data modify entity @s[tag=aj.bonnie.bone.right_hand] ArmorItems[-1].tag.CustomModelData set value 261
data modify entity @s[tag=aj.bonnie.bone.left_arm] ArmorItems[-1].tag.CustomModelData set value 262
data modify entity @s[tag=aj.bonnie.bone.left_hand] ArmorItems[-1].tag.CustomModelData set value 263
data modify entity @s[tag=aj.bonnie.bone.guitar] ArmorItems[-1].tag.CustomModelData set value 264
data modify entity @s[tag=aj.bonnie.bone.eyelids] ArmorItems[-1].tag.CustomModelData set value 254