#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.bonnie.bone.left_leg] ArmorItems[-1].tag.CustomModelData set value 301
data modify entity @s[tag=aj.bonnie.bone.left_lower_leg] ArmorItems[-1].tag.CustomModelData set value 302
data modify entity @s[tag=aj.bonnie.bone.right_leg] ArmorItems[-1].tag.CustomModelData set value 303
data modify entity @s[tag=aj.bonnie.bone.right_lower_leg] ArmorItems[-1].tag.CustomModelData set value 304
data modify entity @s[tag=aj.bonnie.bone.body] ArmorItems[-1].tag.CustomModelData set value 305
data modify entity @s[tag=aj.bonnie.bone.head] ArmorItems[-1].tag.CustomModelData set value 306
data modify entity @s[tag=aj.bonnie.bone.eyes] ArmorItems[-1].tag.CustomModelData set value 307
data modify entity @s[tag=aj.bonnie.bone.pupils] ArmorItems[-1].tag.CustomModelData set value 308
data modify entity @s[tag=aj.bonnie.bone.left_ear] ArmorItems[-1].tag.CustomModelData set value 310
data modify entity @s[tag=aj.bonnie.bone.left_upper_ear] ArmorItems[-1].tag.CustomModelData set value 311
data modify entity @s[tag=aj.bonnie.bone.right_ear] ArmorItems[-1].tag.CustomModelData set value 312
data modify entity @s[tag=aj.bonnie.bone.right_upper_ear] ArmorItems[-1].tag.CustomModelData set value 313
data modify entity @s[tag=aj.bonnie.bone.jaw] ArmorItems[-1].tag.CustomModelData set value 314
data modify entity @s[tag=aj.bonnie.bone.right_arm] ArmorItems[-1].tag.CustomModelData set value 315
data modify entity @s[tag=aj.bonnie.bone.right_hand] ArmorItems[-1].tag.CustomModelData set value 316
data modify entity @s[tag=aj.bonnie.bone.left_arm] ArmorItems[-1].tag.CustomModelData set value 317
data modify entity @s[tag=aj.bonnie.bone.left_hand] ArmorItems[-1].tag.CustomModelData set value 318
data modify entity @s[tag=aj.bonnie.bone.guitar] ArmorItems[-1].tag.CustomModelData set value 19
data modify entity @s[tag=aj.bonnie.bone.eyelids] ArmorItems[-1].tag.CustomModelData set value 309