#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.bonnie.bone.left_leg] ArmorItems[-1].tag.CustomModelData set value 336
data modify entity @s[tag=aj.bonnie.bone.left_lower_leg] ArmorItems[-1].tag.CustomModelData set value 337
data modify entity @s[tag=aj.bonnie.bone.right_leg] ArmorItems[-1].tag.CustomModelData set value 338
data modify entity @s[tag=aj.bonnie.bone.right_lower_leg] ArmorItems[-1].tag.CustomModelData set value 339
data modify entity @s[tag=aj.bonnie.bone.body] ArmorItems[-1].tag.CustomModelData set value 340
data modify entity @s[tag=aj.bonnie.bone.head] ArmorItems[-1].tag.CustomModelData set value 341
data modify entity @s[tag=aj.bonnie.bone.eyes] ArmorItems[-1].tag.CustomModelData set value 342
data modify entity @s[tag=aj.bonnie.bone.pupils] ArmorItems[-1].tag.CustomModelData set value 343
data modify entity @s[tag=aj.bonnie.bone.left_ear] ArmorItems[-1].tag.CustomModelData set value 345
data modify entity @s[tag=aj.bonnie.bone.left_upper_ear] ArmorItems[-1].tag.CustomModelData set value 346
data modify entity @s[tag=aj.bonnie.bone.right_ear] ArmorItems[-1].tag.CustomModelData set value 347
data modify entity @s[tag=aj.bonnie.bone.right_upper_ear] ArmorItems[-1].tag.CustomModelData set value 348
data modify entity @s[tag=aj.bonnie.bone.jaw] ArmorItems[-1].tag.CustomModelData set value 349
data modify entity @s[tag=aj.bonnie.bone.right_arm] ArmorItems[-1].tag.CustomModelData set value 350
data modify entity @s[tag=aj.bonnie.bone.right_hand] ArmorItems[-1].tag.CustomModelData set value 351
data modify entity @s[tag=aj.bonnie.bone.left_arm] ArmorItems[-1].tag.CustomModelData set value 352
data modify entity @s[tag=aj.bonnie.bone.left_hand] ArmorItems[-1].tag.CustomModelData set value 353
data modify entity @s[tag=aj.bonnie.bone.guitar] ArmorItems[-1].tag.CustomModelData set value 19
data modify entity @s[tag=aj.bonnie.bone.eyelids] ArmorItems[-1].tag.CustomModelData set value 344