#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.backstage.anim.easter_egg
execute if score .aj.anim_loop aj.backstage.animating matches 0 run function backstage:animation_loop
scoreboard players set #execute aj.i 1