#Project generated by Animated Java (https://animated-java.dev/)

tp @s ~ ~ ~ ~ ~
scoreboard players operation .this aj.id = @s aj.id
scoreboard players operation .this aj.frame = @s aj.frame
scoreboard players set # aj.i 0
execute if entity @s[tag=aj.backstage.anim.normal] run function backstage:zzz/execute/16
execute if entity @s[tag=aj.backstage.anim.easter_egg] run function backstage:zzz/execute/19
execute if entity @s[tag=aj.backstage.anim.game_over] run function backstage:zzz/execute/22
execute if score # aj.i matches 0 run function backstage:zzz/execute/25
scoreboard players set #execute aj.i 1