#Project generated by Animated Java (https://animated-java.dev/)

tag @s remove aj.backstage.anim.normal
tag @s remove aj.backstage.anim.easter_egg
tag @s remove aj.backstage.anim.game_over
scoreboard players set @s aj.frame 0
scoreboard players operation .this aj.id = @s aj.id
execute as @e[type=minecraft:area_effect_cloud,tag=aj.backstage.bone,distance=..7.287] if score @s aj.id = .this aj.id run function backstage:zzz/execute/14
execute as @e[type=minecraft:armor_stand,tag=aj.backstage.bone,distance=..7.287] if score @s aj.id = .this aj.id run function backstage:zzz/execute/15
scoreboard players set #execute aj.i 1